-- CCE StableOS — legacy operational baseline
--
-- Use only for a brand-new, empty Supabase project before applying the ordered
-- files in supabase/migrations/. This is a reconstruction snapshot of the core
-- tables that existed before migration tracking was introduced; it is not an
-- upgrade script for an existing production database.

begin;

do $$
begin
  if to_regclass('public.income') is not null
     or to_regclass('public.expenses') is not null
     or to_regclass('public.horses') is not null
     or to_regclass('public.breeding') is not null
     or to_regclass('public.schedule') is not null
     or to_regclass('public.instructors') is not null then
    raise exception 'Legacy baseline is for an empty project only; one or more core tables already exist';
  end if;
end $$;

create table public.income (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  due_date date,
  start_time time,
  end_time time,
  customer_name text not null,
  horse_name text,
  activity text,
  qty numeric(12,3) not null default 1,
  amount_bd numeric(12,3) not null default 0,
  paid_bd numeric(12,3) not null default 0,
  notes text,
  status text not null default 'Pending',
  check (qty>0),
  check (amount_bd>=0),
  check (paid_bd>=0)
);

create table public.expenses (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  due_date date,
  category text,
  supplier text not null,
  qty numeric(12,3) not null default 1,
  amount_bd numeric(12,3) not null default 0,
  paid_bd numeric(12,3) not null default 0,
  horse text,
  notes text,
  status text not null default 'Pending',
  check (qty>0),
  check (amount_bd>=0),
  check (paid_bd>=0)
);

create table public.horses (
  id bigint generated by default as identity primary key,
  stable_no text,
  horse_name text not null,
  owner text not null,
  owner_pwd text,
  contact text,
  cpr text,
  address text,
  sex text,
  color text,
  breed text,
  birth_date date,
  microchip text,
  passport text,
  livery_bd numeric(12,3) not null default 0,
  ac_livery_bd numeric(12,3) not null default 0,
  livery_type text,
  payment text,
  status text not null default 'Available',
  start_date date,
  end_date date,
  farrier_name text,
  farrier_date date,
  deworm_date date,
  vaccine_dr text,
  vaccine_date date,
  teeth_date date,
  medicant text,
  med_date date,
  check (livery_bd>=0),
  check (ac_livery_bd>=0)
);

create table public.breeding (
  id bigint generated by default as identity primary key,
  mare_name text not null,
  owner text not null,
  mobile text,
  count integer not null default 1,
  day1 date,
  day2 date,
  day3 date,
  day4 date,
  day5 date,
  day6 date,
  day7 date,
  day8 date,
  day9 date,
  check (count>=0)
);

create table public.schedule (
  id bigint generated by default as identity primary key,
  date date not null,
  start_time time not null,
  end_time time,
  activity text,
  horse_name text,
  customer_name text,
  instructor text,
  status text not null default 'Scheduled',
  notes text,
  color text
);

create table public.instructors (
  id bigint generated by default as identity primary key,
  name text not null,
  pin text,
  phone text,
  active boolean not null default true
);

create index income_date_idx on public.income(date desc,id desc);
create index income_due_idx on public.income(due_date,status);
create index expenses_date_idx on public.expenses(date desc,id desc);
create index expenses_due_idx on public.expenses(due_date,status);
create index horses_name_idx on public.horses(lower(horse_name));
create index horses_owner_idx on public.horses(lower(owner));
create index schedule_date_time_idx on public.schedule(date,start_time);
create index schedule_instructor_idx on public.schedule(lower(instructor),date);
create unique index instructors_name_lower_uidx on public.instructors(lower(name));

comment on table public.income is 'Legacy operational income baseline; later migrations add RBAC, booking linkage and timestamps.';
comment on table public.horses is 'Core horse identity and operational status. Health history is added by later migrations.';

commit;
