// CCE Stable Management Pro — Horse Health Phase 1
const CCE_HEALTH_META={
  'Healthy':{icon:'●',cls:'healthy',label:'Healthy'},'Training':{icon:'●',cls:'training',label:'Training'},
  'Injured':{icon:'●',cls:'injured',label:'Injured'},'Under Treatment':{icon:'●',cls:'treatment',label:'Under Treatment'},
  'Pregnant':{icon:'●',cls:'pregnant',label:'Pregnant'},'Resting':{icon:'●',cls:'resting',label:'Resting'},
  'Isolation':{icon:'●',cls:'isolation',label:'Isolation'},'Critical':{icon:'●',cls:'critical',label:'Critical'}
};
function healthProfileFor(id){return CCE.health.profileFor(horse_health_profiles,id);}
function activeStableHorses(){return CCE.horses.active(horses);}
function horseRecords(id){return CCE.health.records(horse_health_events,id);}
function horseVaccines(id){return CCE.health.vaccines(horse_health_events,id);}
function horseTasks(id){return CCE.health.tasks(horse_health_events,id);}
function cceDaysUntil(d){if(!d)return null;const a=new Date();a.setHours(0,0,0,0);const b=new Date(d+'T00:00:00');return Math.ceil((b-a)/86400000);}
function healthScore(h){const p=healthProfileFor(h.id)||{};let n=100;const status=p.health_status||'Healthy';if(status==='Critical')n-=60;else if(status==='Injured')n-=35;else if(status==='Under Treatment')n-=25;else if(status==='Isolation')n-=30;else if(status==='Resting')n-=10;const open=horseRecords(h.id).filter(r=>r.status!=='Completed'&&r.status!=='Cancelled').length;n-=Math.min(25,open*6);const overdue=horseVaccines(h.id).filter(v=>v.status!=='Completed'&&cceDaysUntil(v.due_date)<0).length;n-=Math.min(20,overdue*8);const tasks=horseTasks(h.id).filter(t=>t.status==='Pending'&&cceDaysUntil(t.due_date)<0).length;n-=Math.min(20,tasks*5);return Math.max(0,Math.min(100,n));}
function scoreClass(n){return n>=85?'good':n>=65?'watch':'risk';}
function healthStatusHTML(status){const m=CCE_HEALTH_META[status]||CCE_HEALTH_META.Healthy;return `<span class="health-status ${m.cls}">${m.icon} ${esc(m.label)}</span>`;}
function getHealthAlerts(){const a=[];activeStableHorses().forEach(h=>{const p=healthProfileFor(h.id)||{};if(['Critical','Injured','Under Treatment','Isolation'].includes(p.health_status))a.push({horse:h,type:p.health_status,date:p.next_review_date,priority:p.health_status==='Critical'?'Urgent':'High',text:p.diagnosis||p.medical_notes||'Health follow-up required'});if(p.expected_foaling_date&&cceDaysUntil(p.expected_foaling_date)<=30)a.push({horse:h,type:'Foaling',date:p.expected_foaling_date,priority:'High',text:'Expected foaling date is approaching'});});horse_vaccinations.filter(v=>v.status!=='Completed'&&cceDaysUntil(v.due_date)<=30).forEach(v=>{const h=activeStableHorses().find(x=>String(x.id)===String(v.horse_id));if(h)a.push({horse:h,type:'Vaccination',date:v.due_date,priority:cceDaysUntil(v.due_date)<0?'Urgent':'Normal',text:v.vaccine_name});});horse_care_tasks.filter(t=>t.status==='Pending'&&cceDaysUntil(t.due_date)<=14).forEach(t=>{const h=activeStableHorses().find(x=>String(x.id)===String(t.horse_id));if(h)a.push({horse:h,type:t.task_type,date:t.due_date,priority:t.priority,text:t.title});});return a.sort((x,y)=>String(x.date||'').localeCompare(String(y.date||'')));}
function renderHorseHealth(){
 const el=document.getElementById('horseHealthDashboard');if(!el)return;
 const activeHorses=activeStableHorses();
 const alerts=getHealthAlerts();const counts={Healthy:0,Injured:0,'Under Treatment':0,Pregnant:0,Resting:0,Isolation:0,Critical:0,Training:0};
 activeHorses.forEach(h=>{const s=(healthProfileFor(h.id)||{}).health_status||'Healthy';counts[s]=(counts[s]||0)+1;});
 const cards=activeHorses.filter(h=>h.horse_name).map(h=>{const p=healthProfileFor(h.id)||{};const st=p.health_status||'Healthy';const score=healthScore(h);const next=[p.next_review_date,...horseVaccines(h.id).filter(v=>v.status!=='Completed').map(v=>v.due_date),...horseTasks(h.id).filter(t=>t.status==='Pending').map(t=>t.due_date)].filter(Boolean).sort()[0];return `<button class="stable-horse-card" onclick="openHorseHealthProfile(${h.id})"><div class="stable-horse-main"><span class="stable-horse-avatar">&#128052;</span><div><strong>${esc(h.horse_name)}</strong><small>${esc(h.owner||'No owner')} · Stable ${esc(h.stable_no||'—')}</small></div></div><div class="stable-horse-badges">${healthStatusHTML(st)}<span class="health-score ${scoreClass(score)}">${score}/100</span></div><div class="stable-horse-meta"><span>${p.diagnosis?esc(p.diagnosis):'No active diagnosis'}</span><span>${next?'Next: '+fmt(next):'No upcoming care'}</span></div></button>`;}).join('');
 el.innerHTML=`<div class="health-stat-grid"><button onclick="filterHealthCards('')"><b>${activeHorses.length}</b><span>Active horses</span></button><button onclick="filterHealthCards('Injured')"><b>${counts.Injured+counts.Critical}</b><span>Injured / Critical</span></button><button onclick="filterHealthCards('Under Treatment')"><b>${counts['Under Treatment']}</b><span>Under treatment</span></button><button onclick="filterHealthCards('Pregnant')"><b>${counts.Pregnant}</b><span>Pregnant mares</span></button><button onclick="filterHealthCards('Isolation')"><b>${counts.Isolation}</b><span>Isolation</span></button></div><div class="health-layout"><section class="health-alert-panel"><div class="health-panel-title"><div><span>Attention required</span><b>${alerts.length} alerts</b></div></div>${alerts.slice(0,12).map(x=>`<button onclick="openHorseHealthProfile(${x.horse.id})" class="health-alert ${String(x.priority).toLowerCase()}"><span>${x.priority==='Urgent'?'!':'•'}</span><div><b>${esc(x.horse.horse_name)} · ${esc(x.type)}</b><small>${esc(x.text)}${x.date?' · '+fmt(x.date):''}</small></div></button>`).join('')||'<div class="health-empty">No urgent health alerts.</div>'}</section><section class="health-horses-panel"><div class="health-panel-title"><div><span>Horse profiles</span><b>Open a horse to manage its health file</b></div><select id="healthStatusFilter" onchange="filterHealthCards(this.value)"><option value="">All health statuses</option>${Object.keys(CCE_HEALTH_META).map(x=>`<option>${x}</option>`).join('')}</select></div><div class="stable-horse-grid" id="stableHorseGrid">${cards}</div></section></div>`;
}
function filterHealthCards(status){const grid=document.getElementById('stableHorseGrid');if(!grid)return;document.querySelectorAll('#stableHorseGrid .stable-horse-card').forEach((card,i)=>{const h=activeStableHorses().filter(x=>x.horse_name)[i];const s=(healthProfileFor(h.id)||{}).health_status||'Healthy';card.style.display=!status||s===status?'grid':'none';});const f=document.getElementById('healthStatusFilter');if(f&&f.value!==status)f.value=status||'';}
function profileTab(id,tab){CCE.horseProfile.selectTab(tab);}
function openHorseHealthProfile(id){CCE.horseProfile.open(id);}
function horseOverviewForm(h,p){return CCE.horseProfile.panels.overview(h,p);}
function medicalPane(h){return CCE.horseProfile.panels.medical(h);}
function vaccinesPane(h){return CCE.horseProfile.panels.vaccines(h);}
function carePane(h){return CCE.horseProfile.panels.care(h);}
function timelinePane(h){return CCE.horseProfile.panels.timeline(h);}
async function saveHorseHealthProfile(id){
  const button=document.querySelector('.horse-profile-modal .profile-actions .btn-green');
  const params={
    p_horse_id:id,
    p_health_status:document.getElementById('hp-status').value,
    p_severity:document.getElementById('hp-severity').value,
    p_diagnosis:document.getElementById('hp-diagnosis').value||null,
    p_veterinarian:document.getElementById('hp-vet').value||null,
    p_next_review_date:document.getElementById('hp-review').value||null,
    p_current_medication:document.getElementById('hp-medication').value||null,
    p_pregnant_since:document.getElementById('hp-pregnant').value||null,
    p_expected_foaling_date:document.getElementById('hp-foaling').value||null,
    p_isolation_reason:null,
    p_allergies:document.getElementById('hp-allergies').value||null,
    p_medical_notes:document.getElementById('hp-notes').value||null
  };
  try{
    if(button){button.disabled=true;button.textContent='Saving…';}
    const saved=await CCE.health.upsertProfile(params);
    if(!saved)throw new Error('The database did not return the saved health profile.');
    await reloadHorseHealth();
    const verified=healthProfileFor(id);
    if(!verified || verified.health_status!==params.p_health_status)throw new Error('Save verification failed. Please retry.');
    openHorseHealthProfile(id);
    setTimeout(()=>{const ok=document.createElement('div');ok.className='cce-save-confirmation';ok.textContent='✓ Health profile saved';document.body.appendChild(ok);setTimeout(()=>ok.remove(),2400);},20);
  }catch(e){showError('Health profile',e);}
  finally{if(button){button.disabled=false;button.textContent='Save health profile';}}
}
function openAddMedical(id){const h=horses.find(x=>String(x.id)===String(id));openModal('Add medical record — '+h.horse_name,`<div class="profile-form"><div class="form-group"><label>Type</label><select id="mr-type">${['Medical','Injury','Treatment','Veterinary Visit','Surgery','Dental','Farrier','Deworming'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="form-group"><label>Date</label><input type="date" id="mr-date" value="${bahrainDateISO()}"></div><div class="form-group wide"><label>Title *</label><input id="mr-title"></div><div class="form-group wide"><label>Diagnosis</label><input id="mr-diagnosis"></div><div class="form-group wide"><label>Treatment</label><textarea id="mr-treatment"></textarea></div><div class="form-group wide"><label>Medication</label><input id="mr-medication"></div><div class="form-group"><label>Veterinarian</label><input id="mr-vet"></div><div class="form-group"><label>Severity</label><select id="mr-severity">${['Low','Moderate','High','Critical'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="form-group"><label>Next review</label><input type="date" id="mr-review"></div><div class="form-group"><label>Status</label><select id="mr-status">${['Open','Monitoring','Completed','Cancelled'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="form-group wide"><label>Notes</label><textarea id="mr-notes"></textarea></div></div><div class="profile-actions"><button class="btn btn-green" onclick="saveMedicalRecord(${id})">Save record</button></div>`);}
async function saveMedicalRecord(id){const title=document.getElementById('mr-title').value.trim();if(!title){alert('Title is required');return;}try{const type=document.getElementById('mr-type').value;await CCE.health.createEvent({horse_id:id,event_scope:'medical',event_type:type,event_date:document.getElementById('mr-date').value,due_date:document.getElementById('mr-review').value||null,title,diagnosis:document.getElementById('mr-diagnosis').value||null,treatment:document.getElementById('mr-treatment').value||null,medication:document.getElementById('mr-medication').value||null,veterinarian:document.getElementById('mr-vet').value||null,severity:document.getElementById('mr-severity').value,priority:document.getElementById('mr-severity').value==='Critical'?'Urgent':document.getElementById('mr-severity').value==='High'?'High':'Normal',status:document.getElementById('mr-status').value,notes:document.getElementById('mr-notes').value||null});await reloadHorseHealth();openHorseHealthProfile(id);setTimeout(()=>profileTab(id,'medical'),0);}catch(e){showError('Medical record',e);}}
function openAddVaccine(id){const h=horses.find(x=>String(x.id)===String(id));openModal('Add vaccination — '+h.horse_name,`<div class="profile-form"><div class="form-group wide"><label>Vaccine name *</label><input id="vx-name"></div><div class="form-group"><label>Administered date</label><input type="date" id="vx-admin"></div><div class="form-group"><label>Due date *</label><input type="date" id="vx-due"></div><div class="form-group"><label>Veterinarian</label><input id="vx-vet"></div><div class="form-group"><label>Batch number</label><input id="vx-batch"></div><div class="form-group wide"><label>Notes</label><textarea id="vx-notes"></textarea></div></div><div class="profile-actions"><button class="btn btn-green" onclick="saveVaccine(${id})">Save vaccination</button></div>`);}
async function saveVaccine(id){const name=document.getElementById('vx-name').value.trim(),due=document.getElementById('vx-due').value;if(!name||!due){alert('Vaccine name and due date are required');return;}try{const administered=document.getElementById('vx-admin').value||null;await CCE.health.createEvent({horse_id:id,event_scope:'vaccination',event_type:'Vaccination',event_date:administered||due,due_date:due,title:name,veterinarian:document.getElementById('vx-vet').value||null,batch_number:document.getElementById('vx-batch').value||null,status:administered?'Completed':'Pending',priority:'Normal',severity:'None',completed_at:administered?new Date(administered+'T00:00:00').toISOString():null,notes:document.getElementById('vx-notes').value||null});await reloadHorseHealth();openHorseHealthProfile(id);setTimeout(()=>profileTab(id,'vaccines'),0);}catch(e){showError('Vaccination',e);}}
async function completeVaccine(vId,hId){try{const today=bahrainDateISO();await CCE.health.updateEvent(vId,{status:'Completed',event_date:today,completed_at:new Date().toISOString()});await reloadHorseHealth();openHorseHealthProfile(hId);setTimeout(()=>profileTab(hId,'vaccines'),0);}catch(e){showError('Vaccination',e);}}
function openAddCare(id){const h=horses.find(x=>String(x.id)===String(id));openModal('Add care task — '+h.horse_name,`<div class="profile-form"><div class="form-group"><label>Type</label><select id="ct-type">${['Veterinary','Medication','Farrier','Dental','Deworming','Vaccination','Rest','Observation','Other'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="form-group"><label>Due date</label><input type="date" id="ct-due" value="${bahrainDateISO()}"></div><div class="form-group wide"><label>Title *</label><input id="ct-title"></div><div class="form-group"><label>Priority</label><select id="ct-priority">${['Low','Normal','High','Urgent'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="form-group"><label>Assigned to</label><input id="ct-assigned"></div><div class="form-group wide"><label>Notes</label><textarea id="ct-notes"></textarea></div></div><div class="profile-actions"><button class="btn btn-green" onclick="saveCareTask(${id})">Save task</button></div>`);}
async function saveCareTask(id){const title=document.getElementById('ct-title').value.trim();if(!title){alert('Title is required');return;}try{const rawType=document.getElementById('ct-type').value;const type=rawType==='Veterinary'?'Veterinary Visit':rawType;const due=document.getElementById('ct-due').value;await CCE.health.createEvent({horse_id:id,event_scope:'care',event_type:type,event_date:due,due_date:due,title,priority:document.getElementById('ct-priority').value,severity:'None',status:'Pending',assigned_to:document.getElementById('ct-assigned').value||null,notes:document.getElementById('ct-notes').value||null});await reloadHorseHealth();openHorseHealthProfile(id);setTimeout(()=>profileTab(id,'care'),0);}catch(e){showError('Care task',e);}}
async function completeCare(id,hId){try{await CCE.health.updateEvent(id,{status:'Completed',completed_at:new Date().toISOString()});await reloadHorseHealth();openHorseHealthProfile(hId);setTimeout(()=>profileTab(hId,'care'),0);setTimeout(()=>{const ok=document.createElement('div');ok.className='cce-save-confirmation';ok.textContent='✓ Care task completed and horse record updated';document.body.appendChild(ok);setTimeout(()=>ok.remove(),2600);},20);}catch(e){showError('Care task',e);}}
async function deleteHealthRecord(table,id,hId){if(!confirm('Delete this record?'))return;try{await CCE.health.deleteEvent(id);await reloadHorseHealth();openHorseHealthProfile(hId);}catch(e){showError('Delete record',e);}}
async function reloadHorseHealth(){
  const loaded=await CCE.health.load();
  let latestHorses=horses;
  try{latestHorses=await sbGet('horses','select=*&limit=500');}catch(error){console.warn('[CCE] Horse summary reload skipped',error);}
  horse_health_profiles=loaded.profiles;
  horse_health_events=loaded.events;
  horses=CCE.health.mergeCompletedSummaries(latestHorses,horse_health_events);
  deriveHealthCollections();
  renderHorseHealth();
  renderHorses();
  if(typeof buildAlerts==='function')buildAlerts();
}
