-- CCE StableOS v4.9.0 — Show Office Sprint 1
-- Competition master data, module permissions and row-level security.

begin;

do $$
begin
  if to_regclass('public.app_permissions') is null
     or to_regclass('public.app_roles') is null
     or to_regclass('public.role_permissions') is null
     or to_regprocedure('public.cce_has_permission(text)') is null
     or to_regprocedure('public.cce_touch_updated_at()') is null then
    raise exception 'CCE access-control foundation must be applied before Show Office Sprint 1';
  end if;
end $$;

insert into public.app_permissions(code,category,name_en,name_ar) values
('show_office.view','Show Office','View Show Office dashboard','عرض لوحة مكتب البطولات'),
('show_office.competitions.view','Show Office','View competitions','عرض البطولات'),
('show_office.competitions.create','Show Office','Create competitions','إضافة بطولة'),
('show_office.competitions.update','Show Office','Update competitions','تعديل البطولات'),
('show_office.competitions.delete','Show Office','Delete competitions','حذف البطولات')
on conflict(code) do update set
  category=excluded.category,
  name_en=excluded.name_en,
  name_ar=excluded.name_ar;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true
from public.app_roles r
join public.app_permissions p on p.code like 'show_office.%'
where r.code in ('super_admin','manager')
on conflict(role_id,permission_code) do update set allowed=true;

create table if not exists public.show_office_competitions (
  id bigint generated by default as identity primary key,
  competition_name text not null,
  competition_date date not null,
  venue text,
  organizer text,
  chief_judge text,
  course_designer text,
  status text not null default 'Draft',
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint show_office_competitions_name_required check (length(trim(competition_name))>0),
  constraint show_office_competitions_status_check check (status in ('Draft','Open','Running','Finished'))
);

create unique index if not exists show_office_competitions_name_date_uidx
  on public.show_office_competitions(lower(trim(competition_name)),competition_date);
create index if not exists show_office_competitions_date_idx
  on public.show_office_competitions(competition_date desc,id desc);
create index if not exists show_office_competitions_status_date_idx
  on public.show_office_competitions(status,competition_date desc);

create or replace function public.cce_show_office_stamp_competition()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if tg_op='INSERT' then
    new.created_by=auth.uid();
    new.created_at=coalesce(new.created_at,now());
  else
    new.created_by=old.created_by;
    new.created_at=old.created_at;
  end if;
  new.updated_by=auth.uid();
  new.updated_at=now();
  return new;
end;
$$;

drop trigger if exists show_office_competitions_stamp on public.show_office_competitions;
create trigger show_office_competitions_stamp
before insert or update on public.show_office_competitions
for each row execute function public.cce_show_office_stamp_competition();

alter table public.show_office_competitions enable row level security;

revoke all on public.show_office_competitions from public,anon,authenticated;
grant select,insert,update,delete on public.show_office_competitions to authenticated;
grant usage,select on sequence public.show_office_competitions_id_seq to authenticated;

drop policy if exists cce_show_office_competitions_select on public.show_office_competitions;
create policy cce_show_office_competitions_select
on public.show_office_competitions for select to authenticated
using (
  public.cce_has_permission('show_office.view')
  or public.cce_has_permission('show_office.competitions.view')
);

drop policy if exists cce_show_office_competitions_insert on public.show_office_competitions;
create policy cce_show_office_competitions_insert
on public.show_office_competitions for insert to authenticated
with check (public.cce_has_permission('show_office.competitions.create'));

drop policy if exists cce_show_office_competitions_update on public.show_office_competitions;
create policy cce_show_office_competitions_update
on public.show_office_competitions for update to authenticated
using (public.cce_has_permission('show_office.competitions.update'))
with check (public.cce_has_permission('show_office.competitions.update'));

drop policy if exists cce_show_office_competitions_delete on public.show_office_competitions;
create policy cce_show_office_competitions_delete
on public.show_office_competitions for delete to authenticated
using (public.cce_has_permission('show_office.competitions.delete'));

revoke all on function public.cce_show_office_stamp_competition() from public,anon,authenticated;

comment on table public.show_office_competitions is
  'Show Office competition master records. Classes and entries are added only in later sprints.';
comment on column public.show_office_competitions.status is
  'Competition lifecycle: Draft, Open, Running or Finished.';

commit;
