-- Country Club Equestrian v3.1.0
-- Database Consolidation & Horse Health persistence hardening
-- Run once after a backup. This migration is transaction-safe and keeps legacy
-- health tables in cce_archive for rollback/audit purposes.

begin;

create schema if not exists cce_archive;
revoke all on schema cce_archive from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 1) Stronger stable relationships without breaking legacy text fields
-- ---------------------------------------------------------------------------
alter table public.horses add column if not exists owner_profile_id uuid;

-- Link horses to the member profile where a single unambiguous owner match exists.
update public.horses h
set owner_profile_id = p.id
from public.profiles p
where h.owner_profile_id is null
  and p.is_active is true
  and coalesce(trim(p.owner_name),'') <> ''
  and lower(trim(h.owner)) = lower(trim(p.owner_name))
  and not exists (
    select 1 from public.profiles p2
    where p2.id <> p.id
      and p2.is_active is true
      and lower(trim(p2.owner_name)) = lower(trim(p.owner_name))
  );

create index if not exists horses_owner_profile_id_idx on public.horses(owner_profile_id);

-- Add foreign keys as NOT VALID so existing historical inconsistencies do not
-- block deployment; new/updated rows are still protected immediately.
do $$
begin
  if not exists (select 1 from pg_constraint where conname='horses_owner_profile_id_fkey') then
    alter table public.horses
      add constraint horses_owner_profile_id_fkey
      foreign key (owner_profile_id) references public.profiles(id)
      on delete set null not valid;
  end if;

  if not exists (select 1 from pg_constraint where conname='profiles_instructor_id_fkey') then
    alter table public.profiles
      add constraint profiles_instructor_id_fkey
      foreign key (instructor_id) references public.instructors(id)
      on delete set null not valid;
  end if;
end $$;

-- One canonical active-horse definition used by health and operations.
create or replace view public.cce_active_horses as
select h.*
from public.horses h
where lower(trim(coalesce(h.status,'')))='available';

revoke all on public.cce_active_horses from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 2) Consolidate medical, vaccination and care rows into one event table
-- ---------------------------------------------------------------------------
create table if not exists public.horse_health_events (
  id bigint generated by default as identity primary key,
  horse_id bigint not null references public.horses(id) on delete cascade,
  event_scope text not null default 'medical' check (event_scope in ('medical','vaccination','care')),
  event_type text not null check (event_type in (
    'Medical','Injury','Treatment','Veterinary Visit','Surgery','Dental','Farrier',
    'Deworming','Vaccination','Medication','Rest','Observation','Other'
  )),
  event_date date not null default current_date,
  due_date date,
  title text not null,
  status text not null default 'Open' check (status in ('Open','Monitoring','Pending','Completed','Overdue','Cancelled')),
  priority text not null default 'Normal' check (priority in ('Low','Normal','High','Urgent')),
  severity text not null default 'None' check (severity in ('None','Low','Moderate','High','Critical')),
  diagnosis text,
  treatment text,
  medication text,
  veterinarian text,
  assigned_to text,
  batch_number text,
  notes text,
  completed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  source_table text,
  source_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_table, source_id)
);

create index if not exists horse_health_events_horse_date_idx
  on public.horse_health_events(horse_id,event_date desc,id desc);
create index if not exists horse_health_events_due_idx
  on public.horse_health_events(due_date,status) where due_date is not null;
create index if not exists horse_health_events_type_idx
  on public.horse_health_events(event_scope,event_type,status);

-- Import legacy health tables if they are still in public.
do $$
begin
  if to_regclass('public.horse_medical_records') is not null then
    insert into public.horse_health_events(
      horse_id,event_scope,event_type,event_date,due_date,title,status,priority,severity,
      diagnosis,treatment,medication,veterinarian,notes,created_by,
      source_table,source_id,created_at,updated_at
    )
    select horse_id,'medical',record_type,event_date,next_review_date,title,
      case status when 'Open' then 'Open' when 'Monitoring' then 'Monitoring'
                  when 'Completed' then 'Completed' else 'Cancelled' end,
      case severity when 'Critical' then 'Urgent' when 'High' then 'High' else 'Normal' end,
      severity,diagnosis,treatment,medication,veterinarian,notes,created_by,
      'horse_medical_records',id,created_at,updated_at
    from public.horse_medical_records
    on conflict(source_table,source_id) do nothing;
  end if;

  if to_regclass('public.horse_vaccinations') is not null then
    insert into public.horse_health_events(
      horse_id,event_scope,event_type,event_date,due_date,title,status,priority,severity,
      veterinarian,batch_number,notes,created_by,completed_at,
      source_table,source_id,created_at,updated_at
    )
    select horse_id,'vaccination','Vaccination',coalesce(administered_date,due_date),due_date,vaccine_name,
      case status when 'Pending' then 'Pending' when 'Completed' then 'Completed'
                  when 'Overdue' then 'Overdue' else 'Cancelled' end,
      case when status='Overdue' then 'High' else 'Normal' end,'None',
      veterinarian,batch_number,notes,created_by,
      case when status='Completed' then coalesce(administered_date,due_date)::timestamptz end,
      'horse_vaccinations',id,created_at,updated_at
    from public.horse_vaccinations
    on conflict(source_table,source_id) do nothing;
  end if;

  if to_regclass('public.horse_care_tasks') is not null then
    insert into public.horse_health_events(
      horse_id,event_scope,event_type,event_date,due_date,title,status,priority,severity,
      assigned_to,notes,created_by,completed_at,
      source_table,source_id,created_at,updated_at
    )
    select horse_id,'care',
      case task_type when 'Veterinary' then 'Veterinary Visit'
                     when 'Vaccination' then 'Vaccination'
                     when 'Medication' then 'Medication'
                     when 'Farrier' then 'Farrier'
                     when 'Dental' then 'Dental'
                     when 'Deworming' then 'Deworming'
                     when 'Rest' then 'Rest'
                     when 'Observation' then 'Observation'
                     else 'Other' end,
      due_date,due_date,title,
      case status when 'Pending' then 'Pending' when 'Completed' then 'Completed' else 'Cancelled' end,
      priority,'None',assigned_to,notes,created_by,completed_at,
      'horse_care_tasks',id,created_at,updated_at
    from public.horse_care_tasks
    on conflict(source_table,source_id) do nothing;
  end if;
end $$;

-- Standard updated_at trigger shared by all health tables.
create or replace function public.cce_touch_updated_at()
returns trigger language plpgsql set search_path=public as $$
begin new.updated_at=now(); return new; end $$;

drop trigger if exists horse_health_events_touch on public.horse_health_events;
create trigger horse_health_events_touch
before update on public.horse_health_events
for each row execute function public.cce_touch_updated_at();

-- ---------------------------------------------------------------------------
-- 3) Reliable one-row health profile upsert through a guarded RPC
-- ---------------------------------------------------------------------------
create or replace function public.cce_upsert_horse_health_profile(
  p_horse_id bigint,
  p_health_status text,
  p_severity text default 'None',
  p_diagnosis text default null,
  p_current_medication text default null,
  p_veterinarian text default null,
  p_next_review_date date default null,
  p_pregnant_since date default null,
  p_expected_foaling_date date default null,
  p_isolation_reason text default null,
  p_allergies text default null,
  p_medical_notes text default null
)
returns public.horse_health_profiles
language plpgsql
security definer
set search_path=public
as $$
declare v_row public.horse_health_profiles;
begin
  if not public.cce_has_permission('horse_health.manage') then
    raise exception 'Permission denied';
  end if;
  if not exists(select 1 from public.horses where id=p_horse_id) then
    raise exception 'Horse not found';
  end if;

  insert into public.horse_health_profiles(
    horse_id,health_status,severity,diagnosis,current_medication,veterinarian,
    next_review_date,pregnant_since,expected_foaling_date,isolation_reason,
    allergies,medical_notes,updated_by
  ) values (
    p_horse_id,p_health_status,p_severity,nullif(trim(p_diagnosis),''),
    nullif(trim(p_current_medication),''),nullif(trim(p_veterinarian),''),
    p_next_review_date,p_pregnant_since,p_expected_foaling_date,
    nullif(trim(p_isolation_reason),''),nullif(trim(p_allergies),''),
    nullif(trim(p_medical_notes),''),auth.uid()
  )
  on conflict(horse_id) do update set
    health_status=excluded.health_status,severity=excluded.severity,
    diagnosis=excluded.diagnosis,current_medication=excluded.current_medication,
    veterinarian=excluded.veterinarian,next_review_date=excluded.next_review_date,
    pregnant_since=excluded.pregnant_since,
    expected_foaling_date=excluded.expected_foaling_date,
    isolation_reason=excluded.isolation_reason,allergies=excluded.allergies,
    medical_notes=excluded.medical_notes,updated_by=auth.uid(),updated_at=now()
  returning * into v_row;

  return v_row;
end $$;

revoke all on function public.cce_upsert_horse_health_profile(bigint,text,text,text,text,text,date,date,date,text,text,text) from public;
grant execute on function public.cce_upsert_horse_health_profile(bigint,text,text,text,text,text,date,date,date,text,text,text) to authenticated;

-- ---------------------------------------------------------------------------
-- 4) Owner functions use the stable UUID relation first, then legacy fallback
-- ---------------------------------------------------------------------------
create or replace function public.cce_member_owner_horses()
returns setof jsonb
language plpgsql stable security definer set search_path=public
as $$
declare v_owner text;
begin
  if not public.cce_has_permission('owner.horses.view') then raise exception 'Permission denied'; end if;
  select owner_name into v_owner from public.profiles where id=auth.uid() and is_active=true;
  return query
  select to_jsonb(h)-'owner_pwd'
  from public.horses h
  where h.owner_profile_id=auth.uid()
     or (h.owner_profile_id is null and coalesce(trim(v_owner),'')<>'' and lower(trim(h.owner))=lower(trim(v_owner)))
  order by h.horse_name;
end $$;

create or replace function public.cce_member_owner_update_horse(
  p_horse_id bigint,p_horse_name text default null,p_contact text default null,
  p_cpr text default null,p_address text default null,p_sex text default null,
  p_color text default null,p_breed text default null,p_birth_date date default null,
  p_microchip text default null,p_passport text default null,p_farrier_name text default null,
  p_farrier_date date default null,p_vaccine_dr text default null,p_vaccine_date date default null,
  p_deworm_date date default null,p_teeth_date date default null,p_medicant text default null,
  p_med_date date default null
)
returns setof jsonb
language plpgsql security definer set search_path=public
as $$
declare v_owner text;
begin
  if not public.cce_has_permission('owner.horses.update') then raise exception 'Permission denied'; end if;
  select owner_name into v_owner from public.profiles where id=auth.uid() and is_active=true;
  return query
  with changed as (
    update public.horses h set
      horse_name=p_horse_name,contact=p_contact,cpr=p_cpr,address=p_address,
      sex=p_sex,color=p_color,breed=p_breed,birth_date=p_birth_date,
      microchip=p_microchip,passport=p_passport,farrier_name=p_farrier_name,
      farrier_date=p_farrier_date,vaccine_dr=p_vaccine_dr,vaccine_date=p_vaccine_date,
      deworm_date=p_deworm_date,teeth_date=p_teeth_date,medicant=p_medicant,
      med_date=p_med_date
    where h.id=p_horse_id
      and (h.owner_profile_id=auth.uid() or
        (h.owner_profile_id is null and coalesce(trim(v_owner),'')<>'' and lower(trim(h.owner))=lower(trim(v_owner))))
    returning h.*
  ) select to_jsonb(changed)-'owner_pwd' from changed;
  if not found then raise exception 'Horse not found or not linked to this owner'; end if;
end $$;

-- ---------------------------------------------------------------------------
-- 5) RLS and permissions for the consolidated event table
-- ---------------------------------------------------------------------------
insert into public.app_permissions(code,category,name_en,name_ar) values
('horse_events.view','Horse Health','View consolidated horse health events','عرض أحداث صحة الخيل'),
('horse_events.manage','Horse Health','Manage consolidated horse health events','إدارة أحداث صحة الخيل')
on conflict(code) do update set category=excluded.category,name_en=excluded.name_en,name_ar=excluded.name_ar;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true from public.app_roles r join public.app_permissions p on p.code in ('horse_events.view','horse_events.manage')
where r.code in ('super_admin','manager')
on conflict(role_id,permission_code) do update set allowed=true;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true from public.app_roles r join public.app_permissions p on p.code='horse_events.view'
where r.code in ('trainer','staff')
on conflict(role_id,permission_code) do nothing;

alter table public.horse_health_events enable row level security;
drop policy if exists cce_hhe_select on public.horse_health_events;
create policy cce_hhe_select on public.horse_health_events for select to authenticated
using (public.cce_has_permission('horse_events.view') or public.cce_has_permission('horse_health.view') or public.cce_has_permission('horse_medical.view') or public.cce_has_permission('horse_vaccinations.view') or public.cce_has_permission('horse_care.view'));
drop policy if exists cce_hhe_insert on public.horse_health_events;
create policy cce_hhe_insert on public.horse_health_events for insert to authenticated
with check (public.cce_has_permission('horse_events.manage') or public.cce_has_permission('horse_medical.manage') or public.cce_has_permission('horse_vaccinations.manage') or public.cce_has_permission('horse_care.manage'));
drop policy if exists cce_hhe_update on public.horse_health_events;
create policy cce_hhe_update on public.horse_health_events for update to authenticated
using (public.cce_has_permission('horse_events.manage') or public.cce_has_permission('horse_medical.manage') or public.cce_has_permission('horse_vaccinations.manage') or public.cce_has_permission('horse_care.manage'))
with check (public.cce_has_permission('horse_events.manage') or public.cce_has_permission('horse_medical.manage') or public.cce_has_permission('horse_vaccinations.manage') or public.cce_has_permission('horse_care.manage'));
drop policy if exists cce_hhe_delete on public.horse_health_events;
create policy cce_hhe_delete on public.horse_health_events for delete to authenticated
using (public.cce_has_permission('horse_events.manage') or public.cce_has_permission('horse_medical.manage') or public.cce_has_permission('horse_vaccinations.manage') or public.cce_has_permission('horse_care.manage'));

grant select,insert,update,delete on public.horse_health_events to authenticated;
grant usage,select on all sequences in schema public to authenticated;

-- Move superseded public tables out of the API schema only after successful copy.
do $$
begin
  if to_regclass('public.horse_medical_records') is not null and to_regclass('cce_archive.horse_medical_records_v300') is null then
    alter table public.horse_medical_records set schema cce_archive;
    alter table cce_archive.horse_medical_records rename to horse_medical_records_v300;
  end if;
  if to_regclass('public.horse_vaccinations') is not null and to_regclass('cce_archive.horse_vaccinations_v300') is null then
    alter table public.horse_vaccinations set schema cce_archive;
    alter table cce_archive.horse_vaccinations rename to horse_vaccinations_v300;
  end if;
  if to_regclass('public.horse_care_tasks') is not null and to_regclass('cce_archive.horse_care_tasks_v300') is null then
    alter table public.horse_care_tasks set schema cce_archive;
    alter table cce_archive.horse_care_tasks rename to horse_care_tasks_v300;
  end if;
end $$;

commit;
