-- CCE StableOS v4.12.0 — Show Office Sprint 4
-- Judge Panel, protected score capture, provisional ranking and atomic restore.

begin;

do $$
begin
  if to_regclass('public.show_office_entries') is null
     or to_regclass('public.show_office_classes') is null
     or to_regclass('public.app_permissions') is null
     or to_regclass('public.app_roles') is null
     or to_regclass('public.role_permissions') is null
     or to_regprocedure('public.cce_has_permission(text)') is null
     or to_regprocedure('public.cce_restore_show_office_module(jsonb)') is null then
    raise exception 'Show Office v4.11.0 must be applied before Sprint 4';
  end if;
end $$;

insert into public.app_roles(code,name_en,name_ar,description,is_system) values
('judge','Judge','حكم','Competition judge with access only to the Show Office judging workflow.',true)
on conflict(code) do update set
  name_en=excluded.name_en,
  name_ar=excluded.name_ar,
  description=excluded.description,
  is_system=true,
  updated_at=now();

insert into public.app_permissions(code,category,name_en,name_ar) values
('show_office.judging.view','Show Office','View Judge Panel and provisional rankings','عرض لوحة الحكام والترتيب المؤقت'),
('show_office.judging.score','Show Office','Record and correct competition scores','تسجيل وتصحيح نتائج المشاركين'),
('show_office.judging.finalize','Show Office','Finalize and lock class results','اعتماد وقفل نتائج الفئة'),
('show_office.judging.reopen','Show Office','Reopen finalized class results','إعادة فتح نتائج الفئة المعتمدة')
on conflict(code) do update set
  category=excluded.category,
  name_en=excluded.name_en,
  name_ar=excluded.name_ar;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true
from public.app_roles r
join public.app_permissions p on p.code like 'show_office.judging.%'
where r.code in ('super_admin','manager')
on conflict(role_id,permission_code) do update set allowed=true;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true
from public.app_roles r
join public.app_permissions p
  on p.code in ('show_office.judging.view','show_office.judging.score')
where r.code='judge'
on conflict(role_id,permission_code) do update set allowed=true;

create table if not exists public.show_office_class_judging (
  class_id bigint primary key references public.show_office_classes(id) on delete restrict,
  status text not null default 'Not Started',
  scoring_profile text not null default 'faults_then_time',
  ruleset_version text not null default 'CCE 2026',
  finalized_by uuid references auth.users(id) on delete set null,
  finalized_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint show_office_class_judging_status_check
    check (status in ('Not Started','Running','Finalized')),
  constraint show_office_class_judging_profile_check
    check (scoring_profile='faults_then_time'),
  constraint show_office_class_judging_ruleset_required
    check (length(trim(ruleset_version))>0),
  constraint show_office_class_judging_ruleset_length_check
    check (char_length(trim(ruleset_version))<=80),
  constraint show_office_class_judging_finalized_check check (
    (status='Finalized' and finalized_at is not null)
    or (status<>'Finalized' and finalized_at is null and finalized_by is null)
  )
);

create table if not exists public.show_office_entry_rounds (
  id bigint generated by default as identity primary key,
  result_ref uuid not null default gen_random_uuid() unique,
  entry_id bigint not null references public.show_office_entries(id) on delete restrict,
  phase text not null,
  time_ms integer,
  faults numeric(8,2),
  refusals smallint not null default 0,
  eliminated boolean not null default false,
  retired boolean not null default false,
  did_not_start boolean not null default false,
  row_version integer not null default 1,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint show_office_entry_rounds_phase_check
    check (phase in ('first_round','jump_off')),
  constraint show_office_entry_rounds_time_check
    check (time_ms is null or (time_ms>0 and time_ms<=86400000)),
  constraint show_office_entry_rounds_faults_check
    check (faults is null or (faults>=0 and faults<=999999.99)),
  constraint show_office_entry_rounds_refusals_check
    check (refusals between 0 and 9),
  constraint show_office_entry_rounds_version_check
    check (row_version>0),
  constraint show_office_entry_rounds_status_check check (
    (case when eliminated then 1 else 0 end)
    +(case when retired then 1 else 0 end)
    +(case when did_not_start then 1 else 0 end)<=1
  ),
  constraint show_office_entry_rounds_complete_check check (
    eliminated or retired or did_not_start
    or (time_ms is not null and faults is not null)
  ),
  constraint show_office_entry_rounds_dns_check check (
    not did_not_start or (time_ms is null and faults is null and refusals=0)
  )
);

create unique index if not exists show_office_entry_rounds_entry_phase_uidx
  on public.show_office_entry_rounds(entry_id,phase);
create index if not exists show_office_entry_rounds_entry_idx
  on public.show_office_entry_rounds(entry_id,id);
create index if not exists show_office_entry_rounds_phase_rank_idx
  on public.show_office_entry_rounds(phase,faults,time_ms,entry_id)
  where not eliminated and not retired and not did_not_start;

create table if not exists public.show_office_score_revisions (
  id bigint generated by default as identity primary key,
  score_ref uuid not null,
  entry_ref uuid not null,
  phase text not null,
  action text not null,
  before_data jsonb,
  after_data jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now(),
  constraint show_office_score_revisions_phase_check
    check (phase in ('first_round','jump_off')),
  constraint show_office_score_revisions_action_check
    check (action in ('create','update','reset'))
);

create index if not exists show_office_score_revisions_score_idx
  on public.show_office_score_revisions(score_ref,changed_at desc,id desc);
create index if not exists show_office_score_revisions_entry_idx
  on public.show_office_score_revisions(entry_ref,changed_at desc,id desc);

create or replace function public.cce_show_office_stamp_judging()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if tg_op='INSERT' then
    new.created_by=auth.uid();
    new.created_at=coalesce(new.created_at,now());
  else
    new.created_by=old.created_by;
    new.created_at=old.created_at;
  end if;
  if new.status<>'Finalized' then
    new.finalized_by=null;
    new.finalized_at=null;
  end if;
  new.updated_by=auth.uid();
  new.updated_at=now();
  return new;
end;
$$;

create or replace function public.cce_show_office_stamp_round()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if tg_op='INSERT' then
    new.created_by=auth.uid();
    new.created_at=coalesce(new.created_at,now());
    new.row_version=1;
  else
    new.result_ref=old.result_ref;
    new.entry_id=old.entry_id;
    new.phase=old.phase;
    new.created_by=old.created_by;
    new.created_at=old.created_at;
    new.row_version=old.row_version+1;
  end if;
  new.updated_by=auth.uid();
  new.updated_at=now();
  return new;
end;
$$;

create or replace function public.cce_show_office_audit_round()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_score_ref uuid;
  v_entry_id bigint;
  v_entry_ref uuid;
  v_phase text;
begin
  if tg_op='INSERT' then
    v_score_ref:=new.result_ref; v_entry_id:=new.entry_id; v_phase:=new.phase;
  else
    v_score_ref:=old.result_ref; v_entry_id:=old.entry_id; v_phase:=old.phase;
  end if;
  select entry_ref into strict v_entry_ref
  from public.show_office_entries where id=v_entry_id;
  insert into public.show_office_score_revisions(
    score_ref,entry_ref,phase,action,before_data,after_data,changed_by
  ) values(
    v_score_ref,v_entry_ref,v_phase,
    case tg_op when 'INSERT' then 'create' when 'UPDATE' then 'update' else 'reset' end,
    case when tg_op='INSERT' then null else to_jsonb(old) end,
    case when tg_op='DELETE' then null else to_jsonb(new) end,
    auth.uid()
  );
  if tg_op='DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists show_office_class_judging_stamp on public.show_office_class_judging;
create trigger show_office_class_judging_stamp
before insert or update on public.show_office_class_judging
for each row execute function public.cce_show_office_stamp_judging();

drop trigger if exists show_office_entry_rounds_00_stamp on public.show_office_entry_rounds;
create trigger show_office_entry_rounds_00_stamp
before insert or update on public.show_office_entry_rounds
for each row execute function public.cce_show_office_stamp_round();

drop trigger if exists show_office_entry_rounds_10_audit on public.show_office_entry_rounds;
create trigger show_office_entry_rounds_10_audit
after insert or update or delete on public.show_office_entry_rounds
for each row execute function public.cce_show_office_audit_round();

alter table public.show_office_class_judging enable row level security;
alter table public.show_office_entry_rounds enable row level security;
alter table public.show_office_score_revisions enable row level security;

revoke all on public.show_office_class_judging,public.show_office_entry_rounds,
  public.show_office_score_revisions from public,anon,authenticated;
grant select on public.show_office_class_judging,public.show_office_entry_rounds to authenticated;
grant select on public.show_office_score_revisions to authenticated;

drop policy if exists cce_show_office_class_judging_select on public.show_office_class_judging;
create policy cce_show_office_class_judging_select
on public.show_office_class_judging for select to authenticated
using (
  public.cce_has_permission('show_office.view')
  or public.cce_has_permission('show_office.judging.view')
);

drop policy if exists cce_show_office_entry_rounds_select on public.show_office_entry_rounds;
create policy cce_show_office_entry_rounds_select
on public.show_office_entry_rounds for select to authenticated
using (
  public.cce_has_permission('show_office.view')
  or public.cce_has_permission('show_office.judging.view')
);

drop policy if exists cce_show_office_score_revisions_select on public.show_office_score_revisions;
create policy cce_show_office_score_revisions_select
on public.show_office_score_revisions for select to authenticated
using (public.cce_has_permission('audit.view'));

create or replace function public.cce_show_office_judging_context()
returns table(
  competition_id bigint,competition_name text,competition_date date,competition_status text,
  class_id bigint,class_number text,class_name text,sort_order integer,height_cm smallint,
  competition_type text,allowed_time_seconds integer,time_limit_seconds integer,jump_off boolean,
  judging_status text,scoring_profile text,ruleset_version text,finalized_at timestamptz,
  entry_count bigint,scored_count bigint
)
language plpgsql
stable
security definer
set search_path=public
as $$
begin
  if not (
    public.cce_has_permission('show_office.view')
    or public.cce_has_permission('show_office.judging.view')
    or public.cce_has_permission('show_office.judging.score')
    or public.cce_has_permission('show_office.judging.finalize')
    or public.cce_has_permission('show_office.judging.reopen')
  ) then
    raise exception 'Permission denied: Show Office judging view permission is required'
      using errcode='42501';
  end if;
  return query
  select
    c.id,c.competition_name,c.competition_date,c.status,
    cl.id,cl.class_number,cl.class_name,cl.sort_order,cl.height_cm,
    cl.competition_type,cl.allowed_time_seconds,cl.time_limit_seconds,cl.jump_off,
    coalesce(j.status,'Not Started'),coalesce(j.scoring_profile,'faults_then_time'),
    coalesce(j.ruleset_version,'CCE 2026'),j.finalized_at,
    count(distinct e.id),
    count(distinct r.entry_id) filter(where r.phase='first_round')
  from public.show_office_classes cl
  join public.show_office_competitions c on c.id=cl.competition_id
  left join public.show_office_class_judging j on j.class_id=cl.id
  left join public.show_office_entries e on e.class_id=cl.id
  left join public.show_office_entry_rounds r on r.entry_id=e.id
  group by c.id,c.competition_name,c.competition_date,c.status,
    cl.id,cl.class_number,cl.class_name,cl.sort_order,cl.height_cm,
    cl.competition_type,cl.allowed_time_seconds,cl.time_limit_seconds,cl.jump_off,
    j.status,j.scoring_profile,j.ruleset_version,j.finalized_at
  order by c.competition_date desc,c.id desc,cl.sort_order,cl.id;
end;
$$;

create or replace function public.cce_show_office_judge_panel(p_class_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v_class jsonb;
  v_rows jsonb;
  v_jump_off boolean;
begin
  if not (
    public.cce_has_permission('show_office.view')
    or public.cce_has_permission('show_office.judging.view')
    or public.cce_has_permission('show_office.judging.score')
    or public.cce_has_permission('show_office.judging.finalize')
    or public.cce_has_permission('show_office.judging.reopen')
  ) then
    raise exception 'Permission denied: Show Office judging view permission is required'
      using errcode='42501';
  end if;
  select cl.jump_off,jsonb_build_object(
    'competition_id',c.id,'competition_name',c.competition_name,
    'competition_date',c.competition_date,'competition_status',c.status,
    'class_id',cl.id,'class_number',cl.class_number,'class_name',cl.class_name,
    'height_cm',cl.height_cm,'competition_type',cl.competition_type,
    'allowed_time_seconds',cl.allowed_time_seconds,
    'time_limit_seconds',cl.time_limit_seconds,'jump_off',cl.jump_off,
    'judging_status',coalesce(j.status,'Not Started'),
    'scoring_profile',coalesce(j.scoring_profile,'faults_then_time'),
    'ruleset_version',coalesce(j.ruleset_version,'CCE 2026'),
    'finalized_at',j.finalized_at
  ) into v_jump_off,v_class
  from public.show_office_classes cl
  join public.show_office_competitions c on c.id=cl.competition_id
  left join public.show_office_class_judging j on j.class_id=cl.id
  where cl.id=p_class_id;
  if v_class is null then
    raise exception 'Show Office class was not found' using errcode='P0002';
  end if;

  with base as (
    select
      e.id as entry_id,e.entry_ref,e.start_number,
      r.rider_name,h.horse_name,s.stable_name,
      fr.id as fr_id,fr.result_ref as fr_ref,fr.time_ms as fr_time,fr.faults as fr_faults,
      fr.refusals as fr_refusals,fr.eliminated as fr_eliminated,
      fr.retired as fr_retired,fr.did_not_start as fr_dns,fr.row_version as fr_version,
      jo.id as jo_id,jo.result_ref as jo_ref,jo.time_ms as jo_time,jo.faults as jo_faults,
      jo.refusals as jo_refusals,jo.eliminated as jo_eliminated,
      jo.retired as jo_retired,jo.did_not_start as jo_dns,jo.row_version as jo_version,
      (
        fr.id is not null
        and not fr.eliminated and not fr.retired and not fr.did_not_start
        and (jo.id is null or (not jo.eliminated and not jo.retired and not jo.did_not_start))
      ) as rankable
    from public.show_office_entries e
    join public.show_office_riders r on r.id=e.rider_id
    join public.show_office_horses h on h.id=e.horse_id
    left join public.show_office_stables s on s.id=e.stable_id
    left join public.show_office_entry_rounds fr
      on fr.entry_id=e.id and fr.phase='first_round'
    left join public.show_office_entry_rounds jo
      on jo.entry_id=e.id and jo.phase='jump_off'
    where e.class_id=p_class_id
  ), ranked as (
    select base.*,
      case when rankable then rank() over(order by
        case
          when rankable and v_jump_off and jo_id is not null then 0
          when rankable then 1 else 9
        end,
        case when v_jump_off and jo_id is not null then jo_faults else fr_faults end,
        case when v_jump_off and jo_id is not null then jo_time else fr_time end
      ) end as place_number
    from base
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'entry_id',entry_id,'entry_ref',entry_ref,'start_number',start_number,
    'rider_name',rider_name,'horse_name',horse_name,'stable_name',stable_name,
    'placing',place_number,
    'first_round',case when fr_id is null then null else jsonb_build_object(
      'id',fr_id,'result_ref',fr_ref,'phase','first_round','time_ms',fr_time,
      'faults',fr_faults,'refusals',fr_refusals,'eliminated',fr_eliminated,
      'retired',fr_retired,'did_not_start',fr_dns,'row_version',fr_version
    ) end,
    'jump_off',case when jo_id is null then null else jsonb_build_object(
      'id',jo_id,'result_ref',jo_ref,'phase','jump_off','time_ms',jo_time,
      'faults',jo_faults,'refusals',jo_refusals,'eliminated',jo_eliminated,
      'retired',jo_retired,'did_not_start',jo_dns,'row_version',jo_version
    ) end
  ) order by start_number,entry_id),'[]'::jsonb) into v_rows
  from ranked;
  return jsonb_build_object('class',v_class,'rows',v_rows);
end;
$$;

create or replace function public.cce_save_show_office_score(
  p_entry_id bigint,p_phase text,p_time_ms integer,p_faults numeric,p_refusals smallint,
  p_eliminated boolean,p_retired boolean,p_did_not_start boolean,
  p_expected_version integer default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_phase text:=lower(trim(coalesce(p_phase,'')));
  v_class_id bigint;
  v_jump_off boolean;
  v_competition_status text;
  v_judging_status text;
  v_existing_id bigint;
  v_existing_version integer;
  v_flags integer;
  v_result jsonb;
begin
  if not public.cce_has_permission('show_office.judging.score') then
    raise exception 'Permission denied: Show Office judging score permission is required'
      using errcode='42501';
  end if;
  select cl.id,cl.jump_off,c.status
    into v_class_id,v_jump_off,v_competition_status
  from public.show_office_entries e
  join public.show_office_classes cl on cl.id=e.class_id
  join public.show_office_competitions c on c.id=cl.competition_id
  where e.id=p_entry_id;
  if v_class_id is null then raise exception 'Show Office entry was not found' using errcode='P0002'; end if;
  if v_competition_status<>'Running' then
    raise exception 'Competition must be Running before scores can be recorded' using errcode='22023';
  end if;
  if v_phase not in ('first_round','jump_off') then
    raise exception 'Score phase must be first_round or jump_off' using errcode='22023';
  end if;
  if v_phase='jump_off' and not v_jump_off then
    raise exception 'This class does not allow a Jump-Off' using errcode='22023';
  end if;
  v_flags:=(case when coalesce(p_eliminated,false) then 1 else 0 end)
    +(case when coalesce(p_retired,false) then 1 else 0 end)
    +(case when coalesce(p_did_not_start,false) then 1 else 0 end);
  if v_flags>1 then
    raise exception 'Eliminated, Retired and DNS are mutually exclusive' using errcode='22023';
  end if;
  if coalesce(p_refusals,0)<0 or coalesce(p_refusals,0)>9 then
    raise exception 'Refusals must be between 0 and 9' using errcode='22023';
  end if;
  if v_flags=0 and (
    p_time_ms is null or p_time_ms<=0 or p_time_ms>86400000
    or p_faults is null or p_faults<0 or p_faults>999999.99
  ) then
    raise exception 'A completed score requires a valid time and faults value' using errcode='22023';
  end if;
  if v_phase='jump_off' and not exists(
    select 1 from public.show_office_entry_rounds
    where entry_id=p_entry_id and phase='first_round'
      and not eliminated and not retired and not did_not_start
  ) then
    raise exception 'A valid first-round score is required before the Jump-Off' using errcode='22023';
  end if;

  insert into public.show_office_class_judging(class_id,status)
  values(v_class_id,'Running') on conflict(class_id) do nothing;
  select status into v_judging_status
  from public.show_office_class_judging where class_id=v_class_id for update;
  if v_judging_status='Finalized' then
    raise exception 'Class results are finalized and locked' using errcode='55000';
  end if;
  if v_judging_status='Not Started' then
    update public.show_office_class_judging set status='Running' where class_id=v_class_id;
  end if;

  select id,row_version into v_existing_id,v_existing_version
  from public.show_office_entry_rounds
  where entry_id=p_entry_id and phase=v_phase
  for update;
  if v_existing_id is null then
    if coalesce(p_expected_version,0)<>0 then
      raise exception 'Score changed on another device; reload before saving'
        using errcode='40001';
    end if;
    insert into public.show_office_entry_rounds(
      entry_id,phase,time_ms,faults,refusals,eliminated,retired,did_not_start
    ) values(
      p_entry_id,v_phase,
      case when v_flags=0 then p_time_ms else null end,
      case when v_flags=0 then p_faults else null end,
      case when coalesce(p_did_not_start,false) then 0 else coalesce(p_refusals,0) end,
      coalesce(p_eliminated,false),coalesce(p_retired,false),coalesce(p_did_not_start,false)
    ) returning id into v_existing_id;
  else
    if p_expected_version is null or p_expected_version<>v_existing_version then
      raise exception 'Score changed on another device; reload before saving'
        using errcode='40001';
    end if;
    update public.show_office_entry_rounds set
      time_ms=case when v_flags=0 then p_time_ms else null end,
      faults=case when v_flags=0 then p_faults else null end,
      refusals=case when coalesce(p_did_not_start,false) then 0 else coalesce(p_refusals,0) end,
      eliminated=coalesce(p_eliminated,false),
      retired=coalesce(p_retired,false),
      did_not_start=coalesce(p_did_not_start,false)
    where id=v_existing_id and row_version=p_expected_version;
    if not found then
      raise exception 'Score changed on another device; reload before saving'
        using errcode='40001';
    end if;
  end if;
  select to_jsonb(r) into strict v_result
  from public.show_office_entry_rounds r where r.id=v_existing_id;
  return v_result;
end;
$$;

create or replace function public.cce_reset_show_office_score(
  p_entry_id bigint,p_phase text,p_expected_version integer
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  v_phase text:=lower(trim(coalesce(p_phase,'')));
  v_class_id bigint;
  v_status text;
  v_competition_status text;
begin
  if not public.cce_has_permission('show_office.judging.score') then
    raise exception 'Permission denied: Show Office judging score permission is required'
      using errcode='42501';
  end if;
  if v_phase not in ('first_round','jump_off') then
    raise exception 'Score phase must be first_round or jump_off' using errcode='22023';
  end if;
  select e.class_id,coalesce(j.status,'Not Started'),c.status
    into v_class_id,v_status,v_competition_status
  from public.show_office_entries e
  join public.show_office_classes cl on cl.id=e.class_id
  join public.show_office_competitions c on c.id=cl.competition_id
  left join public.show_office_class_judging j on j.class_id=e.class_id
  where e.id=p_entry_id;
  if v_class_id is null then raise exception 'Show Office entry was not found' using errcode='P0002'; end if;
  if v_competition_status<>'Running' then
    raise exception 'Competition must be Running before scores can be reset' using errcode='22023';
  end if;
  if v_status='Finalized' then raise exception 'Class results are finalized and locked' using errcode='55000'; end if;
  if v_phase='first_round' and exists(
    select 1 from public.show_office_entry_rounds
    where entry_id=p_entry_id and phase='jump_off'
  ) then
    raise exception 'Reset the Jump-Off score before resetting the first round' using errcode='55000';
  end if;
  delete from public.show_office_entry_rounds
  where entry_id=p_entry_id and phase=v_phase and row_version=p_expected_version;
  if not found then
    raise exception 'Score changed on another device; reload before resetting'
      using errcode='40001';
  end if;
  if not exists(
    select 1 from public.show_office_entry_rounds r
    join public.show_office_entries e on e.id=r.entry_id
    where e.class_id=v_class_id
  ) then
    update public.show_office_class_judging set status='Not Started'
    where class_id=v_class_id;
  end if;
  return true;
end;
$$;

create or replace function public.cce_finalize_show_office_class(p_class_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_entry_count bigint;
  v_missing bigint;
  v_competition_status text;
  v_result jsonb;
begin
  if not public.cce_has_permission('show_office.judging.finalize') then
    raise exception 'Permission denied: Show Office judging finalize permission is required'
      using errcode='42501';
  end if;
  select c.status,count(e.id),
    count(e.id) filter(where r.id is null)
  into v_competition_status,v_entry_count,v_missing
  from public.show_office_classes cl
  join public.show_office_competitions c on c.id=cl.competition_id
  left join public.show_office_entries e on e.class_id=cl.id
  left join public.show_office_entry_rounds r
    on r.entry_id=e.id and r.phase='first_round'
  where cl.id=p_class_id
  group by c.status;
  if v_competition_status is null then raise exception 'Show Office class was not found' using errcode='P0002'; end if;
  if v_competition_status<>'Running' then
    raise exception 'Competition must be Running before results can be finalized' using errcode='22023';
  end if;
  if v_entry_count=0 then raise exception 'A class without entries cannot be finalized' using errcode='22023'; end if;
  if v_missing>0 then
    raise exception 'Every entry requires a first-round result before finalization' using errcode='22023';
  end if;
  insert into public.show_office_class_judging(
    class_id,status,scoring_profile,ruleset_version,finalized_by,finalized_at
  ) values(p_class_id,'Finalized','faults_then_time','CCE 2026',auth.uid(),now())
  on conflict(class_id) do update set
    status='Finalized',finalized_by=auth.uid(),finalized_at=now();
  select to_jsonb(j) into strict v_result
  from public.show_office_class_judging j where j.class_id=p_class_id;
  return v_result;
end;
$$;

create or replace function public.cce_reopen_show_office_class(p_class_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_result jsonb;
begin
  if not public.cce_has_permission('show_office.judging.reopen') then
    raise exception 'Permission denied: Show Office judging reopen permission is required'
      using errcode='42501';
  end if;
  update public.show_office_class_judging
  set status='Running',finalized_by=null,finalized_at=null
  where class_id=p_class_id and status='Finalized';
  if not found then
    raise exception 'Finalized class results were not found' using errcode='P0002';
  end if;
  select to_jsonb(j) into strict v_result
  from public.show_office_class_judging j where j.class_id=p_class_id;
  return v_result;
end;
$$;

-- Preserve the complete v4.11 restore implementation as a private helper.
do $$
begin
  if to_regprocedure('public.cce_restore_show_office_through_entries(jsonb)') is null then
    alter function public.cce_restore_show_office_module(jsonb)
      rename to cce_restore_show_office_through_entries;
  end if;
end $$;
revoke all on function public.cce_restore_show_office_through_entries(jsonb)
  from public,anon,authenticated;

create or replace function public.cce_restore_show_office_judging_data(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_judging jsonb:=coalesce(p_payload->'judging','[]'::jsonb);
  v_scores jsonb:=coalesce(p_payload->'scores','[]'::jsonb);
  v_row jsonb;
  v_date date;
  v_class_id bigint;
  v_entry_id bigint;
  v_ref uuid;
  v_phase text;
  v_flags integer;
  v_inserted_id bigint;
  v_judging_total integer:=0; v_judging_imported integer:=0; v_judging_duplicates integer:=0;
  v_score_total integer:=0; v_score_imported integer:=0; v_score_duplicates integer:=0;
begin
  if jsonb_typeof(v_judging)<>'array' or jsonb_typeof(v_scores)<>'array' then
    raise exception 'Show Office judging and scores must be JSON arrays' using errcode='22023';
  end if;
  v_judging_total:=jsonb_array_length(v_judging);
  v_score_total:=jsonb_array_length(v_scores);
  if v_judging_total+v_score_total>0
     and not public.cce_has_permission('show_office.judging.score') then
    raise exception 'Permission denied: Show Office judging score permission is required'
      using errcode='42501';
  end if;
  if exists(
    select 1 from jsonb_array_elements(v_judging) item
    where item->>'status'='Finalized'
  ) and not public.cce_has_permission('show_office.judging.finalize') then
    raise exception 'Permission denied: Show Office judging finalize permission is required'
      using errcode='42501';
  end if;

  for v_row in select value from jsonb_array_elements(v_judging) loop
    if jsonb_typeof(v_row)<>'object' then
      raise exception 'Show Office backup judging record must be an object' using errcode='22023';
    end if;
    begin v_date:=(v_row->>'competition_date')::date; exception when others then
      raise exception 'Show Office backup judging record has an invalid date' using errcode='22023'; end;
    if coalesce(v_row->>'competition_date','')!~'^\d{4}-\d{2}-\d{2}$'
       or to_char(v_date,'YYYY-MM-DD')<>v_row->>'competition_date'
       or length(trim(coalesce(v_row->>'competition_name','')))=0
       or length(trim(coalesce(v_row->>'class_number','')))=0
       or v_row->>'status' not in ('Not Started','Running','Finalized')
       or coalesce(v_row->>'scoring_profile','faults_then_time')<>'faults_then_time'
       or length(trim(coalesce(v_row->>'ruleset_version','CCE 2026')))=0
       or char_length(trim(coalesce(v_row->>'ruleset_version','CCE 2026')))>80 then
      raise exception 'Show Office backup judging record is invalid' using errcode='22023';
    end if;
    select cl.id into v_class_id
    from public.show_office_classes cl
    join public.show_office_competitions c on c.id=cl.competition_id
    where lower(trim(c.competition_name))=lower(trim(v_row->>'competition_name'))
      and c.competition_date=v_date
      and lower(trim(cl.class_number))=lower(trim(v_row->>'class_number'));
    if v_class_id is null then
      raise exception 'Show Office backup judging record references an unavailable class'
        using errcode='23503';
    end if;
    v_inserted_id:=null;
    insert into public.show_office_class_judging(
      class_id,status,scoring_profile,ruleset_version,finalized_by,finalized_at
    ) values(
      v_class_id,v_row->>'status','faults_then_time',
      trim(coalesce(v_row->>'ruleset_version','CCE 2026')),
      case when v_row->>'status'='Finalized' then auth.uid() else null end,
      case when v_row->>'status'='Finalized' then now() else null end
    ) on conflict do nothing returning class_id into v_inserted_id;
    if v_inserted_id is null then v_judging_duplicates:=v_judging_duplicates+1;
    else v_judging_imported:=v_judging_imported+1; end if;
  end loop;

  for v_row in select value from jsonb_array_elements(v_scores) loop
    if jsonb_typeof(v_row)<>'object' then
      raise exception 'Show Office backup score must be an object' using errcode='22023';
    end if;
    begin
      v_ref:=(v_row->>'result_ref')::uuid;
      v_entry_id=null;
      v_phase:=lower(trim(v_row->>'phase'));
    exception when others then
      raise exception 'Show Office backup score has invalid references' using errcode='22023';
    end;
    if v_phase not in ('first_round','jump_off')
       or jsonb_typeof(v_row->'refusals')<>'number'
       or (v_row->>'refusals')::numeric<>trunc((v_row->>'refusals')::numeric)
       or ((v_row->>'refusals')::integer not between 0 and 9) then
      raise exception 'Show Office backup score has invalid phase or refusals' using errcode='22023';
    end if;
    if (v_row?'eliminated' and jsonb_typeof(v_row->'eliminated')<>'boolean')
       or (v_row?'retired' and jsonb_typeof(v_row->'retired')<>'boolean')
       or (v_row?'did_not_start' and jsonb_typeof(v_row->'did_not_start')<>'boolean') then
      raise exception 'Show Office backup score flags must be boolean' using errcode='22023';
    end if;
    v_flags:=(case when coalesce((v_row->>'eliminated')::boolean,false) then 1 else 0 end)
      +(case when coalesce((v_row->>'retired')::boolean,false) then 1 else 0 end)
      +(case when coalesce((v_row->>'did_not_start')::boolean,false) then 1 else 0 end);
    if v_flags>1 then raise exception 'Show Office backup score has conflicting statuses' using errcode='22023'; end if;
    if v_flags=0 and (
      jsonb_typeof(v_row->'time_ms')<>'number'
      or (v_row->>'time_ms')::numeric<>trunc((v_row->>'time_ms')::numeric)
      or (v_row->>'time_ms')::integer<=0 or (v_row->>'time_ms')::integer>86400000
      or jsonb_typeof(v_row->'faults')<>'number'
      or (v_row->>'faults')::numeric<0 or (v_row->>'faults')::numeric>999999.99
    ) then
      raise exception 'Show Office backup completed score has invalid time or faults' using errcode='22023';
    end if;
    select id into v_entry_id from public.show_office_entries
    where entry_ref=(v_row->>'entry_ref')::uuid;
    if v_entry_id is null then
      raise exception 'Show Office backup score references an unavailable entry'
        using errcode='23503';
    end if;
    if v_phase='jump_off' and not exists(
      select 1 from public.show_office_entries e
      join public.show_office_classes cl on cl.id=e.class_id
      where e.id=v_entry_id and cl.jump_off
    ) then
      raise exception 'Show Office backup score uses Jump-Off for an incompatible class'
        using errcode='22023';
    end if;
    if not exists(
      select 1
      from public.show_office_entries e
      join public.show_office_class_judging j on j.class_id=e.class_id
      where e.id=v_entry_id
    ) then
      raise exception 'Show Office backup score requires a judging record for its class'
        using errcode='22023';
    end if;
    v_inserted_id:=null;
    insert into public.show_office_entry_rounds(
      result_ref,entry_id,phase,time_ms,faults,refusals,eliminated,retired,did_not_start
    ) values(
      v_ref,v_entry_id,v_phase,
      case when v_flags=0 then (v_row->>'time_ms')::integer else null end,
      case when v_flags=0 then (v_row->>'faults')::numeric else null end,
      case when coalesce((v_row->>'did_not_start')::boolean,false)
        then 0 else (v_row->>'refusals')::smallint end,
      coalesce((v_row->>'eliminated')::boolean,false),
      coalesce((v_row->>'retired')::boolean,false),
      coalesce((v_row->>'did_not_start')::boolean,false)
    ) on conflict do nothing returning id into v_inserted_id;
    if v_inserted_id is null then v_score_duplicates:=v_score_duplicates+1;
    else v_score_imported:=v_score_imported+1; end if;
  end loop;

  if exists(
    select 1 from public.show_office_entry_rounds jo
    join public.show_office_entries e on e.id=jo.entry_id
    left join public.show_office_entry_rounds fr
      on fr.entry_id=e.id and fr.phase='first_round'
    where jo.phase='jump_off'
      and (fr.id is null or fr.eliminated or fr.retired or fr.did_not_start)
  ) then
    raise exception 'Show Office restored Jump-Off score requires a valid first round'
      using errcode='22023';
  end if;
  if exists(
    select 1 from public.show_office_class_judging j
    left join public.show_office_entries e on e.class_id=j.class_id
    left join public.show_office_entry_rounds r
      on r.entry_id=e.id and r.phase='first_round'
    where j.status='Finalized'
    group by j.class_id
    having count(e.id)=0 or count(e.id) filter(where r.id is null)>0
  ) then
    raise exception 'Show Office restored finalized class has unscored entries'
      using errcode='22023';
  end if;
  return jsonb_build_object(
    'total',v_judging_total+v_score_total,
    'imported',v_judging_imported+v_score_imported,
    'duplicates',v_judging_duplicates+v_score_duplicates,
    'invalid',0,
    'entities',jsonb_build_object(
      'judging',jsonb_build_object(
        'total',v_judging_total,'imported',v_judging_imported,
        'duplicates',v_judging_duplicates,'invalid',0
      ),
      'scores',jsonb_build_object(
        'total',v_score_total,'imported',v_score_imported,
        'duplicates',v_score_duplicates,'invalid',0
      )
    )
  );
end;
$$;

revoke all on function public.cce_restore_show_office_judging_data(jsonb)
  from public,anon,authenticated;

create or replace function public.cce_restore_show_office_module(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_core jsonb;
  v_judging jsonb;
begin
  if p_payload is null or jsonb_typeof(p_payload)<>'object' then
    raise exception 'Show Office restore payload must be a JSON object' using errcode='22023';
  end if;
  select public.cce_restore_show_office_through_entries(p_payload) into v_core;
  select public.cce_restore_show_office_judging_data(p_payload) into v_judging;
  return jsonb_build_object(
    'module','showOffice',
    'total',(v_core->>'total')::integer+(v_judging->>'total')::integer,
    'imported',(v_core->>'imported')::integer+(v_judging->>'imported')::integer,
    'duplicates',(v_core->>'duplicates')::integer+(v_judging->>'duplicates')::integer,
    'invalid',0,
    'entities',(v_core->'entities')||(v_judging->'entities')
  );
end;
$$;

revoke all on function public.cce_show_office_stamp_judging() from public,anon,authenticated;
revoke all on function public.cce_show_office_stamp_round() from public,anon,authenticated;
revoke all on function public.cce_show_office_audit_round() from public,anon,authenticated;
revoke all on function public.cce_show_office_judging_context() from public,anon,authenticated;
revoke all on function public.cce_show_office_judge_panel(bigint) from public,anon,authenticated;
revoke all on function public.cce_save_show_office_score(bigint,text,integer,numeric,smallint,boolean,boolean,boolean,integer)
  from public,anon,authenticated;
revoke all on function public.cce_reset_show_office_score(bigint,text,integer)
  from public,anon,authenticated;
revoke all on function public.cce_finalize_show_office_class(bigint)
  from public,anon,authenticated;
revoke all on function public.cce_reopen_show_office_class(bigint)
  from public,anon,authenticated;
revoke all on function public.cce_restore_show_office_module(jsonb)
  from public,anon,authenticated;

grant execute on function public.cce_show_office_judging_context() to authenticated;
grant execute on function public.cce_show_office_judge_panel(bigint) to authenticated;
grant execute on function public.cce_save_show_office_score(bigint,text,integer,numeric,smallint,boolean,boolean,boolean,integer)
  to authenticated;
grant execute on function public.cce_reset_show_office_score(bigint,text,integer)
  to authenticated;
grant execute on function public.cce_finalize_show_office_class(bigint)
  to authenticated;
grant execute on function public.cce_reopen_show_office_class(bigint)
  to authenticated;
grant execute on function public.cce_restore_show_office_module(jsonb)
  to authenticated;

comment on table public.show_office_class_judging is
  'Per-class judging lifecycle and rules profile. Finalized rows lock score changes.';
comment on table public.show_office_entry_rounds is
  'Official first-round and Jump-Off score snapshots with optimistic concurrency.';
comment on table public.show_office_score_revisions is
  'Append-only server audit history for every score create, correction and reset.';
comment on function public.cce_show_office_judge_panel(bigint) is
  'Returns a permission-filtered Judge Panel and provisional faults-then-time ranking.';
comment on function public.cce_restore_show_office_module(jsonb) is
  'Atomically restores portable Show Office data through Sprint 4 judging and scores.';

commit;
