-- CCE StableOS v4.11.0 — Show Office Sprint 3
-- Permanent rider/horse/stable registries, competition entries, guarded CRUD,
-- least-privilege directories and atomic module restore.

begin;

do $$
begin
  if to_regclass('public.show_office_competitions') is null
     or to_regclass('public.show_office_classes') is null
     or to_regclass('public.horses') is null
     or to_regclass('public.app_permissions') is null
     or to_regclass('public.app_roles') is null
     or to_regclass('public.role_permissions') is null
     or to_regprocedure('public.cce_has_permission(text)') is null
     or to_regprocedure('public.cce_restore_show_office_module(jsonb)') is null then
    raise exception 'Show Office v4.10.0 must be applied before Sprint 3';
  end if;
end $$;

insert into public.app_permissions(code,category,name_en,name_ar) values
('show_office.entries.view','Show Office','View competition entries','عرض مشاركات البطولات'),
('show_office.entries.create','Show Office','Create competition entries','إضافة مشاركات البطولات'),
('show_office.entries.update','Show Office','Update competition entries','تعديل مشاركات البطولات'),
('show_office.entries.delete','Show Office','Delete competition entries','حذف مشاركات البطولات')
on conflict(code) do update set
  category=excluded.category,
  name_en=excluded.name_en,
  name_ar=excluded.name_ar;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true
from public.app_roles r
join public.app_permissions p on p.code like 'show_office.entries.%'
where r.code in ('super_admin','manager')
on conflict(role_id,permission_code) do update set allowed=true;

create table if not exists public.show_office_riders (
  id bigint generated by default as identity primary key,
  rider_ref uuid not null default gen_random_uuid() unique,
  rider_name text not null,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint show_office_riders_name_required check (length(trim(rider_name))>0),
  constraint show_office_riders_name_length_check check (char_length(trim(rider_name))<=180)
);

create table if not exists public.show_office_stables (
  id bigint generated by default as identity primary key,
  stable_ref uuid not null default gen_random_uuid() unique,
  stable_name text not null,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint show_office_stables_name_required check (length(trim(stable_name))>0),
  constraint show_office_stables_name_length_check check (char_length(trim(stable_name))<=180)
);

create unique index if not exists show_office_stables_name_uidx
  on public.show_office_stables(lower(trim(stable_name)));

create table if not exists public.show_office_horses (
  id bigint generated by default as identity primary key,
  horse_ref uuid not null default gen_random_uuid() unique,
  core_horse_id bigint unique references public.horses(id) on delete set null,
  horse_name text not null,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint show_office_horses_name_required check (length(trim(horse_name))>0),
  constraint show_office_horses_name_length_check check (char_length(trim(horse_name))<=180)
);

create table if not exists public.show_office_entries (
  id bigint generated by default as identity primary key,
  entry_ref uuid not null default gen_random_uuid() unique,
  class_id bigint not null references public.show_office_classes(id) on delete restrict,
  start_number integer not null,
  rider_id bigint not null references public.show_office_riders(id) on delete restrict,
  horse_id bigint not null references public.show_office_horses(id) on delete restrict,
  stable_id bigint references public.show_office_stables(id) on delete restrict,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint show_office_entries_start_number_check check (start_number>0)
);

create unique index if not exists show_office_entries_class_start_uidx
  on public.show_office_entries(class_id,start_number);
create unique index if not exists show_office_entries_class_pair_uidx
  on public.show_office_entries(class_id,rider_id,horse_id);
create index if not exists show_office_entries_class_order_idx
  on public.show_office_entries(class_id,start_number,id);
create index if not exists show_office_entries_rider_idx
  on public.show_office_entries(rider_id);
create index if not exists show_office_entries_horse_idx
  on public.show_office_entries(horse_id);
create index if not exists show_office_entries_stable_idx
  on public.show_office_entries(stable_id) where stable_id is not null;
create unique index if not exists show_office_riders_name_uidx
  on public.show_office_riders(lower(trim(rider_name)));
create unique index if not exists show_office_horses_name_uidx
  on public.show_office_horses(lower(trim(horse_name)));

create or replace function public.cce_show_office_stamp_entry_record()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if tg_op='INSERT' then
    new.created_by=auth.uid();
    new.created_at=coalesce(new.created_at,now());
  else
    new.created_by=old.created_by;
    new.created_at=old.created_at;
  end if;
  new.updated_by=auth.uid();
  new.updated_at=now();
  return new;
end;
$$;

create or replace function public.cce_show_office_sync_core_horse_name()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if new.core_horse_id is not null then
    select trim(h.horse_name) into new.horse_name
    from public.horses h where h.id=new.core_horse_id;
    if not found then raise exception 'Core horse not found' using errcode='23503'; end if;
  else
    new.horse_name=trim(new.horse_name);
  end if;
  return new;
end;
$$;

drop trigger if exists show_office_riders_stamp on public.show_office_riders;
create trigger show_office_riders_stamp before insert or update on public.show_office_riders
for each row execute function public.cce_show_office_stamp_entry_record();
drop trigger if exists show_office_stables_stamp on public.show_office_stables;
create trigger show_office_stables_stamp before insert or update on public.show_office_stables
for each row execute function public.cce_show_office_stamp_entry_record();
drop trigger if exists show_office_horses_00_sync on public.show_office_horses;
create trigger show_office_horses_00_sync before insert or update on public.show_office_horses
for each row execute function public.cce_show_office_sync_core_horse_name();
drop trigger if exists show_office_horses_stamp on public.show_office_horses;
create trigger show_office_horses_stamp before insert or update on public.show_office_horses
for each row execute function public.cce_show_office_stamp_entry_record();
drop trigger if exists show_office_entries_stamp on public.show_office_entries;
create trigger show_office_entries_stamp before insert or update on public.show_office_entries
for each row execute function public.cce_show_office_stamp_entry_record();

alter table public.show_office_riders enable row level security;
alter table public.show_office_horses enable row level security;
alter table public.show_office_stables enable row level security;
alter table public.show_office_entries enable row level security;

revoke all on public.show_office_riders,public.show_office_horses,
  public.show_office_stables,public.show_office_entries from public,anon,authenticated;
grant select on public.show_office_riders,public.show_office_horses,public.show_office_stables to authenticated;
grant select,insert,update,delete on public.show_office_entries to authenticated;
grant usage,select on sequence public.show_office_entries_id_seq to authenticated;

drop policy if exists cce_show_office_riders_select on public.show_office_riders;
create policy cce_show_office_riders_select on public.show_office_riders for select to authenticated
using (public.cce_has_permission('show_office.view') or public.cce_has_permission('show_office.entries.view'));
drop policy if exists cce_show_office_horses_select on public.show_office_horses;
create policy cce_show_office_horses_select on public.show_office_horses for select to authenticated
using (public.cce_has_permission('show_office.view') or public.cce_has_permission('show_office.entries.view'));
drop policy if exists cce_show_office_stables_select on public.show_office_stables;
create policy cce_show_office_stables_select on public.show_office_stables for select to authenticated
using (public.cce_has_permission('show_office.view') or public.cce_has_permission('show_office.entries.view'));

drop policy if exists cce_show_office_entries_select on public.show_office_entries;
create policy cce_show_office_entries_select on public.show_office_entries for select to authenticated
using (public.cce_has_permission('show_office.view') or public.cce_has_permission('show_office.entries.view'));
drop policy if exists cce_show_office_entries_insert on public.show_office_entries;
create policy cce_show_office_entries_insert on public.show_office_entries for insert to authenticated
with check (public.cce_has_permission('show_office.entries.create'));
drop policy if exists cce_show_office_entries_update on public.show_office_entries;
create policy cce_show_office_entries_update on public.show_office_entries for update to authenticated
using (public.cce_has_permission('show_office.entries.update'))
with check (public.cce_has_permission('show_office.entries.update'));
drop policy if exists cce_show_office_entries_delete on public.show_office_entries;
create policy cce_show_office_entries_delete on public.show_office_entries for delete to authenticated
using (public.cce_has_permission('show_office.entries.delete'));

create or replace function public.cce_show_office_entry_context()
returns table(
  competition_id bigint,competition_name text,competition_date date,
  class_id bigint,class_number text,class_name text,sort_order integer
)
language plpgsql
stable
security definer
set search_path=public
as $$
begin
  if not (
    public.cce_has_permission('show_office.view')
    or public.cce_has_permission('show_office.entries.view')
    or public.cce_has_permission('show_office.entries.create')
    or public.cce_has_permission('show_office.entries.update')
  ) then
    raise exception 'Permission denied: Show Office entry permission is required' using errcode='42501';
  end if;
  return query
  select c.id,c.competition_name,c.competition_date,
         cl.id,cl.class_number,cl.class_name,cl.sort_order
  from public.show_office_competitions c
  join public.show_office_classes cl on cl.competition_id=c.id
  order by c.competition_date desc,c.id desc,cl.sort_order,cl.id;
end;
$$;

create or replace function public.cce_show_office_entry_directory(
  p_query text default '',p_limit integer default 50
)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v_query text:=lower(trim(coalesce(p_query,'')));
  v_limit integer:=greatest(1,least(coalesce(p_limit,50),100));
begin
  if not (
    public.cce_has_permission('show_office.view')
    or public.cce_has_permission('show_office.entries.view')
    or public.cce_has_permission('show_office.entries.create')
    or public.cce_has_permission('show_office.entries.update')
  ) then
    raise exception 'Permission denied: Show Office entry permission is required' using errcode='42501';
  end if;
  return jsonb_build_object(
    'riders',coalesce((select jsonb_agg(to_jsonb(x) order by x.rider_name,x.id) from (
      select r.id,r.rider_ref,r.rider_name from public.show_office_riders r
      where v_query='' or lower(r.rider_name) like '%'||v_query||'%'
      order by r.rider_name,r.id limit v_limit
    ) x),'[]'::jsonb),
    'horses',coalesce((select jsonb_agg(to_jsonb(x) order by x.horse_name,x.id) from (
      select h.id,h.horse_ref,h.core_horse_id,h.horse_name from public.show_office_horses h
      where v_query='' or lower(h.horse_name) like '%'||v_query||'%'
      order by h.horse_name,h.id limit v_limit
    ) x),'[]'::jsonb),
    'stables',coalesce((select jsonb_agg(to_jsonb(x) order by x.stable_name,x.id) from (
      select s.id,s.stable_ref,s.stable_name from public.show_office_stables s
      where v_query='' or lower(s.stable_name) like '%'||v_query||'%'
      order by s.stable_name,s.id limit v_limit
    ) x),'[]'::jsonb),
    'core_horses',coalesce((select jsonb_agg(to_jsonb(x) order by x.horse_name,x.id) from (
      select h.id,h.horse_name,h.stable_no from public.horses h
      where length(trim(coalesce(h.horse_name,'')))>0
        and (v_query='' or lower(h.horse_name) like '%'||v_query||'%'
          or lower(coalesce(h.stable_no,'')) like '%'||v_query||'%')
      order by h.horse_name,h.id limit v_limit
    ) x),'[]'::jsonb)
  );
end;
$$;

create or replace function public.cce_show_office_entries_page(
  p_class_id bigint,p_search text default '',p_limit integer default 100,p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v_search text:=lower(trim(coalesce(p_search,'')));
  v_limit integer:=greatest(1,least(coalesce(p_limit,100),200));
  v_offset integer:=greatest(0,coalesce(p_offset,0));
  v_total integer;
  v_rows jsonb;
begin
  if not (public.cce_has_permission('show_office.view') or public.cce_has_permission('show_office.entries.view')) then
    raise exception 'Permission denied: Show Office entry view permission is required' using errcode='42501';
  end if;
  if not exists(select 1 from public.show_office_classes where id=p_class_id) then
    raise exception 'Competition class not found' using errcode='23503';
  end if;
  select count(*) into v_total
  from public.show_office_entries e
  join public.show_office_riders r on r.id=e.rider_id
  join public.show_office_horses h on h.id=e.horse_id
  left join public.show_office_stables s on s.id=e.stable_id
  where e.class_id=p_class_id and (
    v_search='' or e.start_number::text like '%'||v_search||'%'
    or lower(r.rider_name) like '%'||v_search||'%'
    or lower(h.horse_name) like '%'||v_search||'%'
    or lower(coalesce(s.stable_name,'')) like '%'||v_search||'%'
  );
  select coalesce(jsonb_agg(to_jsonb(x) order by x.start_number,x.id),'[]'::jsonb) into v_rows
  from (
    select e.id,e.entry_ref,e.class_id,e.start_number,e.rider_id,r.rider_name,
           e.horse_id,h.horse_name,e.stable_id,s.stable_name,e.created_at,e.updated_at
    from public.show_office_entries e
    join public.show_office_riders r on r.id=e.rider_id
    join public.show_office_horses h on h.id=e.horse_id
    left join public.show_office_stables s on s.id=e.stable_id
    where e.class_id=p_class_id and (
      v_search='' or e.start_number::text like '%'||v_search||'%'
      or lower(r.rider_name) like '%'||v_search||'%'
      or lower(h.horse_name) like '%'||v_search||'%'
      or lower(coalesce(s.stable_name,'')) like '%'||v_search||'%'
    )
    order by e.start_number,e.id limit v_limit offset v_offset
  ) x;
  return jsonb_build_object('total',v_total,'rows',v_rows,'limit',v_limit,'offset',v_offset);
end;
$$;

create or replace function public.cce_save_show_office_entry(
  p_class_id bigint,
  p_start_number integer,
  p_entry_id bigint default null,
  p_rider_id bigint default null,
  p_rider_name text default null,
  p_horse_id bigint default null,
  p_core_horse_id bigint default null,
  p_horse_name text default null,
  p_stable_id bigint default null,
  p_stable_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_rider_id bigint;
  v_horse_id bigint;
  v_stable_id bigint;
  v_entry_id bigint;
  v_name text;
  v_result jsonb;
begin
  if p_entry_id is null then
    if not public.cce_has_permission('show_office.entries.create') then
      raise exception 'Permission denied: Show Office entry create permission is required' using errcode='42501';
    end if;
  else
    if not public.cce_has_permission('show_office.entries.update') then
      raise exception 'Permission denied: Show Office entry update permission is required' using errcode='42501';
    end if;
    if not exists(select 1 from public.show_office_entries where id=p_entry_id) then
      raise exception 'Competition entry not found' using errcode='P0002';
    end if;
  end if;
  if not exists(select 1 from public.show_office_classes where id=p_class_id) then
    raise exception 'Competition class not found' using errcode='23503';
  end if;
  if p_start_number is null or p_start_number<=0 then
    raise exception 'Start number must be a positive whole number' using errcode='22023';
  end if;

  if p_rider_id is not null then
    select id into v_rider_id from public.show_office_riders where id=p_rider_id;
    if v_rider_id is null then raise exception 'Rider not found' using errcode='23503'; end if;
  else
    v_name:=trim(coalesce(p_rider_name,''));
    if v_name='' or char_length(v_name)>180 then raise exception 'A valid rider name is required' using errcode='22023'; end if;
    insert into public.show_office_riders(rider_name) values(v_name)
    on conflict do nothing returning id into v_rider_id;
    if v_rider_id is null then
      select id into v_rider_id from public.show_office_riders where lower(trim(rider_name))=lower(v_name);
    end if;
  end if;

  if p_horse_id is not null then
    select id into v_horse_id from public.show_office_horses where id=p_horse_id;
    if v_horse_id is null then raise exception 'Horse not found' using errcode='23503'; end if;
  elsif p_core_horse_id is not null then
    insert into public.show_office_horses(core_horse_id,horse_name)
    select h.id,h.horse_name from public.horses h where h.id=p_core_horse_id
    on conflict do nothing
    returning id into v_horse_id;
    if v_horse_id is null then
      select sh.id into v_horse_id
      from public.show_office_horses sh
      join public.horses h on h.id=p_core_horse_id
      where sh.core_horse_id=p_core_horse_id or lower(trim(sh.horse_name))=lower(trim(h.horse_name))
      order by (sh.core_horse_id=p_core_horse_id) desc limit 1;
    end if;
    if v_horse_id is null then raise exception 'Core horse not found' using errcode='23503'; end if;
  else
    v_name:=trim(coalesce(p_horse_name,''));
    if v_name='' or char_length(v_name)>180 then raise exception 'A valid horse name is required' using errcode='22023'; end if;
    insert into public.show_office_horses(horse_name) values(v_name)
    on conflict do nothing returning id into v_horse_id;
    if v_horse_id is null then
      select id into v_horse_id from public.show_office_horses where lower(trim(horse_name))=lower(v_name);
    end if;
  end if;

  if p_stable_id is not null then
    select id into v_stable_id from public.show_office_stables where id=p_stable_id;
    if v_stable_id is null then raise exception 'Stable or club not found' using errcode='23503'; end if;
  elsif trim(coalesce(p_stable_name,''))<>'' then
    v_name:=trim(p_stable_name);
    if char_length(v_name)>180 then raise exception 'Stable or club name must be 180 characters or fewer' using errcode='22023'; end if;
    insert into public.show_office_stables(stable_name) values(v_name)
    on conflict do nothing returning id into v_stable_id;
    if v_stable_id is null then
      select id into v_stable_id from public.show_office_stables where lower(trim(stable_name))=lower(v_name);
    end if;
  end if;

  if p_entry_id is null then
    insert into public.show_office_entries(class_id,start_number,rider_id,horse_id,stable_id)
    values(p_class_id,p_start_number,v_rider_id,v_horse_id,v_stable_id)
    returning id into v_entry_id;
  else
    update public.show_office_entries set
      class_id=p_class_id,start_number=p_start_number,rider_id=v_rider_id,
      horse_id=v_horse_id,stable_id=v_stable_id
    where id=p_entry_id returning id into v_entry_id;
  end if;

  select to_jsonb(x) into v_result from (
    select e.id,e.entry_ref,e.class_id,e.start_number,e.rider_id,r.rider_name,
           e.horse_id,h.horse_name,e.stable_id,s.stable_name,e.created_at,e.updated_at
    from public.show_office_entries e
    join public.show_office_riders r on r.id=e.rider_id
    join public.show_office_horses h on h.id=e.horse_id
    left join public.show_office_stables s on s.id=e.stable_id
    where e.id=v_entry_id
  ) x;
  return v_result;
end;
$$;

-- Preserve the v4.10 competitions/classes restore implementation as a private
-- helper so the public v4.11 RPC can add registries and entries atomically.
do $$
begin
  if to_regprocedure('public.cce_restore_show_office_competitions_classes(jsonb)') is null then
    alter function public.cce_restore_show_office_module(jsonb)
      rename to cce_restore_show_office_competitions_classes;
  end if;
end $$;

revoke all on function public.cce_restore_show_office_competitions_classes(jsonb)
  from public,anon,authenticated;

create or replace function public.cce_restore_show_office_entry_data(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_riders jsonb:=coalesce(p_payload->'riders','[]'::jsonb);
  v_horses jsonb:=coalesce(p_payload->'horses','[]'::jsonb);
  v_stables jsonb:=coalesce(p_payload->'stables','[]'::jsonb);
  v_entries jsonb:=coalesce(p_payload->'entries','[]'::jsonb);
  v_row jsonb;
  v_ref uuid;
  v_stable_ref uuid;
  v_date date;
  v_class_id bigint;
  v_rider_id bigint;
  v_horse_id bigint;
  v_stable_id bigint;
  v_inserted_id bigint;
  v_rider_total integer:=0; v_rider_imported integer:=0; v_rider_duplicates integer:=0;
  v_horse_total integer:=0; v_horse_imported integer:=0; v_horse_duplicates integer:=0;
  v_stable_total integer:=0; v_stable_imported integer:=0; v_stable_duplicates integer:=0;
  v_entry_total integer:=0; v_entry_imported integer:=0; v_entry_duplicates integer:=0;
begin
  if jsonb_typeof(v_riders)<>'array' or jsonb_typeof(v_horses)<>'array'
     or jsonb_typeof(v_stables)<>'array' or jsonb_typeof(v_entries)<>'array' then
    raise exception 'Show Office riders, horses, stables and entries must be JSON arrays' using errcode='22023';
  end if;
  v_rider_total:=jsonb_array_length(v_riders);
  v_horse_total:=jsonb_array_length(v_horses);
  v_stable_total:=jsonb_array_length(v_stables);
  v_entry_total:=jsonb_array_length(v_entries);
  if v_rider_total+v_horse_total+v_stable_total+v_entry_total>0
     and not public.cce_has_permission('show_office.entries.create') then
    raise exception 'Permission denied: Show Office entry create permission is required' using errcode='42501';
  end if;

  for v_row in select value from jsonb_array_elements(v_riders) loop
    if jsonb_typeof(v_row)<>'object' or jsonb_typeof(v_row->'rider_ref')<>'string'
       or jsonb_typeof(v_row->'rider_name')<>'string' then
      raise exception 'Show Office backup rider has an invalid structure' using errcode='22023';
    end if;
    begin v_ref:=(v_row->>'rider_ref')::uuid; exception when others then
      raise exception 'Show Office backup rider has an invalid rider_ref' using errcode='22023'; end;
    if length(trim(v_row->>'rider_name'))=0 or char_length(trim(v_row->>'rider_name'))>180 then
      raise exception 'Show Office backup rider has an invalid rider_name' using errcode='22023';
    end if;
    v_inserted_id:=null;
    insert into public.show_office_riders(rider_ref,rider_name)
    values(v_ref,trim(v_row->>'rider_name')) on conflict do nothing returning id into v_inserted_id;
    if v_inserted_id is null then v_rider_duplicates:=v_rider_duplicates+1; else v_rider_imported:=v_rider_imported+1; end if;
  end loop;

  for v_row in select value from jsonb_array_elements(v_horses) loop
    if jsonb_typeof(v_row)<>'object' or jsonb_typeof(v_row->'horse_ref')<>'string'
       or jsonb_typeof(v_row->'horse_name')<>'string' then
      raise exception 'Show Office backup horse has an invalid structure' using errcode='22023';
    end if;
    begin v_ref:=(v_row->>'horse_ref')::uuid; exception when others then
      raise exception 'Show Office backup horse has an invalid horse_ref' using errcode='22023'; end;
    if length(trim(v_row->>'horse_name'))=0 or char_length(trim(v_row->>'horse_name'))>180 then
      raise exception 'Show Office backup horse has an invalid horse_name' using errcode='22023';
    end if;
    v_inserted_id:=null;
    insert into public.show_office_horses(horse_ref,horse_name)
    values(v_ref,trim(v_row->>'horse_name')) on conflict do nothing returning id into v_inserted_id;
    if v_inserted_id is null then v_horse_duplicates:=v_horse_duplicates+1; else v_horse_imported:=v_horse_imported+1; end if;
  end loop;

  for v_row in select value from jsonb_array_elements(v_stables) loop
    if jsonb_typeof(v_row)<>'object' or jsonb_typeof(v_row->'stable_ref')<>'string'
       or jsonb_typeof(v_row->'stable_name')<>'string' then
      raise exception 'Show Office backup stable has an invalid structure' using errcode='22023';
    end if;
    begin v_ref:=(v_row->>'stable_ref')::uuid; exception when others then
      raise exception 'Show Office backup stable has an invalid stable_ref' using errcode='22023'; end;
    if length(trim(v_row->>'stable_name'))=0 or char_length(trim(v_row->>'stable_name'))>180 then
      raise exception 'Show Office backup stable has an invalid stable_name' using errcode='22023';
    end if;
    v_inserted_id:=null;
    insert into public.show_office_stables(stable_ref,stable_name)
    values(v_ref,trim(v_row->>'stable_name')) on conflict do nothing returning id into v_inserted_id;
    if v_inserted_id is null then v_stable_duplicates:=v_stable_duplicates+1; else v_stable_imported:=v_stable_imported+1; end if;
  end loop;

  for v_row in select value from jsonb_array_elements(v_entries) loop
    if jsonb_typeof(v_row)<>'object' then raise exception 'Show Office backup entry must be an object' using errcode='22023'; end if;
    begin
      v_ref:=(v_row->>'entry_ref')::uuid;
      v_rider_id=null; v_horse_id=null; v_stable_id=null;
      v_date:=(v_row->>'competition_date')::date;
    exception when others then
      raise exception 'Show Office backup entry has invalid references or date' using errcode='22023';
    end;
    if coalesce(v_row->>'competition_date','')!~'^\d{4}-\d{2}-\d{2}$'
       or to_char(v_date,'YYYY-MM-DD')<>v_row->>'competition_date'
       or length(trim(coalesce(v_row->>'competition_name','')))=0
       or length(trim(coalesce(v_row->>'class_number','')))=0 then
      raise exception 'Show Office backup entry has an invalid class reference' using errcode='22023';
    end if;
    if jsonb_typeof(v_row->'start_number')<>'number'
       or (v_row->>'start_number')::numeric<>trunc((v_row->>'start_number')::numeric)
       or (v_row->>'start_number')::numeric<=0
       or (v_row->>'start_number')::numeric>2147483647 then
      raise exception 'Show Office backup entry has an invalid start_number' using errcode='22023';
    end if;
    begin
      select cl.id into strict v_class_id
      from public.show_office_classes cl
      join public.show_office_competitions c on c.id=cl.competition_id
      where lower(trim(c.competition_name))=lower(trim(v_row->>'competition_name'))
        and c.competition_date=v_date
        and lower(trim(cl.class_number))=lower(trim(v_row->>'class_number'));
    exception when no_data_found then
      raise exception 'Show Office backup entry references an unavailable class' using errcode='23503';
    end;
    select id into v_rider_id from public.show_office_riders where rider_ref=(v_row->>'rider_ref')::uuid;
    if v_rider_id is null then
      select r.id into v_rider_id
      from public.show_office_riders r
      join jsonb_array_elements(v_riders) source
        on (source->>'rider_ref')::uuid=(v_row->>'rider_ref')::uuid
       and lower(trim(r.rider_name))=lower(trim(source->>'rider_name'))
      limit 1;
    end if;
    select id into v_horse_id from public.show_office_horses where horse_ref=(v_row->>'horse_ref')::uuid;
    if v_horse_id is null then
      select h.id into v_horse_id
      from public.show_office_horses h
      join jsonb_array_elements(v_horses) source
        on (source->>'horse_ref')::uuid=(v_row->>'horse_ref')::uuid
       and lower(trim(h.horse_name))=lower(trim(source->>'horse_name'))
      limit 1;
    end if;
    if nullif(v_row->>'stable_ref','') is not null then
      v_stable_ref:=(v_row->>'stable_ref')::uuid;
      select id into v_stable_id from public.show_office_stables where stable_ref=v_stable_ref;
      if v_stable_id is null then
        select s.id into v_stable_id
        from public.show_office_stables s
        join jsonb_array_elements(v_stables) source
          on (source->>'stable_ref')::uuid=v_stable_ref
         and lower(trim(s.stable_name))=lower(trim(source->>'stable_name'))
        limit 1;
      end if;
    end if;
    if v_rider_id is null or v_horse_id is null
       or (nullif(v_row->>'stable_ref','') is not null and v_stable_id is null) then
      raise exception 'Show Office backup entry references an unavailable rider, horse or stable' using errcode='23503';
    end if;
    v_inserted_id:=null;
    insert into public.show_office_entries(entry_ref,class_id,start_number,rider_id,horse_id,stable_id)
    values(v_ref,v_class_id,(v_row->>'start_number')::integer,v_rider_id,v_horse_id,v_stable_id)
    on conflict do nothing returning id into v_inserted_id;
    if v_inserted_id is null then v_entry_duplicates:=v_entry_duplicates+1; else v_entry_imported:=v_entry_imported+1; end if;
  end loop;

  return jsonb_build_object(
    'total',v_rider_total+v_horse_total+v_stable_total+v_entry_total,
    'imported',v_rider_imported+v_horse_imported+v_stable_imported+v_entry_imported,
    'duplicates',v_rider_duplicates+v_horse_duplicates+v_stable_duplicates+v_entry_duplicates,
    'invalid',0,
    'entities',jsonb_build_object(
      'riders',jsonb_build_object('total',v_rider_total,'imported',v_rider_imported,'duplicates',v_rider_duplicates,'invalid',0),
      'horses',jsonb_build_object('total',v_horse_total,'imported',v_horse_imported,'duplicates',v_horse_duplicates,'invalid',0),
      'stables',jsonb_build_object('total',v_stable_total,'imported',v_stable_imported,'duplicates',v_stable_duplicates,'invalid',0),
      'entries',jsonb_build_object('total',v_entry_total,'imported',v_entry_imported,'duplicates',v_entry_duplicates,'invalid',0)
    )
  );
end;
$$;

revoke all on function public.cce_restore_show_office_entry_data(jsonb) from public,anon,authenticated;

create or replace function public.cce_restore_show_office_module(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_core jsonb;
  v_entry jsonb;
begin
  if p_payload is null or jsonb_typeof(p_payload)<>'object' then
    raise exception 'Show Office restore payload must be a JSON object' using errcode='22023';
  end if;
  select public.cce_restore_show_office_competitions_classes(
    jsonb_build_object(
      'competitions',p_payload->'competitions',
      'classes',coalesce(p_payload->'classes','[]'::jsonb)
    )
  ) into v_core;
  select public.cce_restore_show_office_entry_data(p_payload) into v_entry;
  return jsonb_build_object(
    'module','showOffice',
    'total',(v_core->>'total')::integer+(v_entry->>'total')::integer,
    'imported',(v_core->>'imported')::integer+(v_entry->>'imported')::integer,
    'duplicates',(v_core->>'duplicates')::integer+(v_entry->>'duplicates')::integer,
    'invalid',0,
    'entities',(v_core->'entities')||(v_entry->'entities')
  );
end;
$$;

revoke all on function public.cce_show_office_stamp_entry_record() from public,anon,authenticated;
revoke all on function public.cce_show_office_sync_core_horse_name() from public,anon,authenticated;
revoke all on function public.cce_show_office_entry_context() from public,anon,authenticated;
revoke all on function public.cce_show_office_entry_directory(text,integer) from public,anon,authenticated;
revoke all on function public.cce_show_office_entries_page(bigint,text,integer,integer) from public,anon,authenticated;
revoke all on function public.cce_save_show_office_entry(bigint,integer,bigint,bigint,text,bigint,bigint,text,bigint,text) from public,anon,authenticated;
revoke all on function public.cce_restore_show_office_module(jsonb) from public,anon,authenticated;
grant execute on function public.cce_show_office_entry_context() to authenticated;
grant execute on function public.cce_show_office_entry_directory(text,integer) to authenticated;
grant execute on function public.cce_show_office_entries_page(bigint,text,integer,integer) to authenticated;
grant execute on function public.cce_save_show_office_entry(bigint,integer,bigint,bigint,text,bigint,bigint,text,bigint,text) to authenticated;
grant execute on function public.cce_restore_show_office_module(jsonb) to authenticated;

comment on table public.show_office_riders is 'Permanent Show Office rider registry; no guest rider model is used.';
comment on table public.show_office_horses is 'Competition horse registry; core_horse_id links existing stable horses without duplicating operational data.';
comment on table public.show_office_stables is 'Reusable stable and club registry for competition entries.';
comment on table public.show_office_entries is 'Class entries protected by permanent rider, horse and optional stable references.';
comment on function public.cce_save_show_office_entry(bigint,integer,bigint,bigint,text,bigint,bigint,text,bigint,text) is
  'Atomically resolves or creates permanent entry registries and saves one competition entry.';
comment on function public.cce_restore_show_office_module(jsonb) is
  'Atomically restores portable Show Office competitions, classes, registries and entries.';

commit;
