-- Country Club Equestrian — unified member portal, roles and permissions
-- Corrected build 2026-07-11: fixes role-permission seed JOIN syntax.
-- Run once after backing up the database. This migration is designed for the
-- existing CCE tables: income, expenses, horses, breeding, schedule, instructors.

begin;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

grant usage on schema public to anon, authenticated;

create table if not exists public.app_roles (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[a-z0-9_]+$'),
  name_en text not null,
  name_ar text,
  description text,
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_permissions (
  code text primary key check (code ~ '^[a-z0-9_.]+$'),
  category text not null,
  name_en text not null,
  name_ar text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
  role_id uuid not null references public.app_roles(id) on delete cascade,
  permission_code text not null references public.app_permissions(code) on delete cascade,
  allowed boolean not null default true,
  primary key (role_id, permission_code)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null default '',
  phone text,
  role_id uuid references public.app_roles(id) on delete set null,
  is_active boolean not null default true,
  owner_name text,
  instructor_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_permissions (
  user_id uuid not null references public.profiles(id) on delete cascade,
  permission_code text not null references public.app_permissions(code) on delete cascade,
  allowed boolean not null,
  primary key (user_id, permission_code)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  ts timestamptz not null default now(),
  actor text,
  action text,
  table_name text,
  record_id text,
  before_data jsonb,
  after_data jsonb
);

create index if not exists profiles_role_id_idx on public.profiles(role_id);
create index if not exists profiles_owner_name_idx on public.profiles(lower(owner_name));
create index if not exists profiles_instructor_id_idx on public.profiles(instructor_id);
create index if not exists role_permissions_permission_idx on public.role_permissions(permission_code);
create index if not exists user_permissions_permission_idx on public.user_permissions(permission_code);
create index if not exists audit_logs_ts_idx on public.audit_logs(ts desc);

insert into public.app_permissions(code,category,name_en,name_ar) values
('dashboard.view','Dashboard','View dashboard','عرض لوحة التحكم'),
('income.view','Finance','View income','عرض الإيرادات'),
('income.create','Finance','Create income','إضافة إيراد'),
('income.update','Finance','Update income','تعديل الإيرادات'),
('income.delete','Finance','Delete income','حذف الإيرادات'),
('expenses.view','Finance','View expenses','عرض المصروفات'),
('expenses.create','Finance','Create expenses','إضافة مصروف'),
('expenses.update','Finance','Update expenses','تعديل المصروفات'),
('expenses.delete','Finance','Delete expenses','حذف المصروفات'),
('reports.view','Finance','View financial reports','عرض التقارير المالية'),
('bookings.view','Bookings','View guest bookings','عرض حجوزات الزوار'),
('bookings.create','Bookings','Create bookings','إضافة حجز'),
('bookings.update','Bookings','Update bookings','تعديل الحجوزات'),
('bookings.delete','Bookings','Delete bookings','حذف الحجوزات'),
('schedule.view','Schedule','View all schedules','عرض جميع الجداول'),
('schedule.create','Schedule','Create schedule entries','إضافة موعد'),
('schedule.update','Schedule','Update schedule entries','تعديل المواعيد'),
('schedule.delete','Schedule','Delete schedule entries','حذف المواعيد'),
('schedule.view_own','Schedule','View own trainer schedule','عرض جدول المدرب الخاص'),
('schedule.update_own','Schedule','Update own trainer schedule','تحديث جدول المدرب الخاص'),
('instructors.view','Instructors','View instructors','عرض المدربين'),
('instructors.create','Instructors','Create instructors','إضافة مدرب'),
('instructors.update','Instructors','Update instructors','تعديل المدربين'),
('instructors.delete','Instructors','Delete instructors','حذف المدربين'),
('horses.view','Horses','View all horses','عرض جميع الخيل'),
('horses.create','Horses','Create horses','إضافة حصان'),
('horses.update','Horses','Update horses','تعديل الخيل'),
('horses.delete','Horses','Delete horses','حذف الخيل'),
('owner.horses.view','Owner Portal','View linked owner horses','عرض خيل المالك المرتبطة'),
('owner.horses.update','Owner Portal','Update linked owner horses','تعديل خيل المالك المرتبطة'),
('breeding.view','Breeding','View breeding records','عرض سجلات التناسل'),
('breeding.create','Breeding','Create breeding records','إضافة سجل تناسل'),
('breeding.update','Breeding','Update breeding records','تعديل سجل التناسل'),
('breeding.delete','Breeding','Delete breeding records','حذف سجل التناسل'),
('users.manage','Administration','Manage users','إدارة المستخدمين'),
('roles.manage','Administration','Manage roles and permissions','إدارة الأدوار والصلاحيات'),
('audit.view','Administration','View audit log','عرض سجل التغييرات'),
('settings.manage','Administration','Manage application tools and settings','إدارة أدوات وإعدادات التطبيق'),
('notifications.view','Administration','View operational notifications','عرض التنبيهات')
on conflict (code) do update set
  category=excluded.category,
  name_en=excluded.name_en,
  name_ar=excluded.name_ar;

insert into public.app_roles(code,name_en,name_ar,description,is_system) values
('super_admin','Super Admin','مدير النظام','Full access including users, roles and permissions.',true),
('manager','Manager','مدير','Operational and financial management without changing system roles.',true),
('reception','Reception','الاستقبال','Guest bookings, schedules and basic horse lookup.',true),
('accountant','Accountant','محاسب','Income, expenses, receipts and financial reports.',true),
('trainer','Trainer','مدرب','Own training schedule and session notes.',true),
('owner','Horse Owner','مالك خيل','Linked horse information only.',true),
('staff','Staff','موظف','Minimal base account; grant required permissions as needed.',true)
on conflict (code) do update set
  name_en=excluded.name_en,
  name_ar=excluded.name_ar,
  description=excluded.description,
  is_system=true,
  updated_at=now();

-- Seed role permissions. Existing custom changes are retained unless listed here.
insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true from public.app_roles r cross join public.app_permissions p
where r.code='super_admin'
on conflict (role_id,permission_code) do update set allowed=true;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true from public.app_roles r join public.app_permissions p on p.code in (
'dashboard.view','income.view','income.create','income.update','income.delete',
'expenses.view','expenses.create','expenses.update','expenses.delete','reports.view',
'bookings.view','bookings.create','bookings.update','bookings.delete',
'schedule.view','schedule.create','schedule.update','schedule.delete',
'instructors.view','instructors.create','instructors.update',
'horses.view','horses.create','horses.update','horses.delete',
'breeding.view','breeding.create','breeding.update','breeding.delete',
'users.manage','audit.view','settings.manage','notifications.view'
) where r.code='manager'
on conflict (role_id,permission_code) do nothing;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true from public.app_roles r join public.app_permissions p on p.code in (
'dashboard.view','bookings.view','bookings.create','bookings.update',
'schedule.view','schedule.create','schedule.update','horses.view','instructors.view','notifications.view'
) where r.code='reception'
on conflict (role_id,permission_code) do nothing;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true from public.app_roles r join public.app_permissions p on p.code in (
'dashboard.view','income.view','income.create','income.update','expenses.view','expenses.create','expenses.update','reports.view','audit.view'
) where r.code='accountant'
on conflict (role_id,permission_code) do nothing;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true from public.app_roles r join public.app_permissions p on p.code in ('schedule.view_own','schedule.update_own')
where r.code='trainer'
on conflict (role_id,permission_code) do nothing;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true from public.app_roles r join public.app_permissions p on p.code in ('owner.horses.view','owner.horses.update')
where r.code='owner'
on conflict (role_id,permission_code) do nothing;

create or replace function public.cce_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at=now();
  return new;
end;
$$;

drop trigger if exists app_roles_touch_updated_at on public.app_roles;
create trigger app_roles_touch_updated_at before update on public.app_roles
for each row execute function public.cce_touch_updated_at();

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at before update on public.profiles
for each row execute function public.cce_touch_updated_at();

create or replace function public.cce_default_role_id()
returns uuid language sql stable security definer set search_path=public as $$
  select id from public.app_roles where code='staff' limit 1;
$$;

create or replace function public.cce_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.profiles(id,email,full_name,phone,role_id,is_active)
  values(
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    new.phone,
    public.cce_default_role_id(),
    true
  )
  on conflict (id) do update set email=excluded.email;
  return new;
end;
$$;

drop trigger if exists cce_on_auth_user_created on auth.users;
create trigger cce_on_auth_user_created
after insert on auth.users for each row execute function public.cce_handle_new_auth_user();

-- Add profiles for any Auth users that predate this migration.
insert into public.profiles(id,email,full_name,phone,role_id,is_active)
select u.id,u.email,coalesce(u.raw_user_meta_data->>'full_name',''),u.phone,public.cce_default_role_id(),true
from auth.users u
on conflict (id) do update set email=excluded.email;

create or replace function public.cce_has_permission(p_permission text)
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select coalesce((
    select case
      when p.is_active is not true then false
      when up.allowed is not null then up.allowed
      when r.code='super_admin' then true
      else coalesce(rp.allowed,false)
    end
    from public.profiles p
    left join public.app_roles r on r.id=p.role_id
    left join public.user_permissions up on up.user_id=p.id and up.permission_code=p_permission
    left join public.role_permissions rp on rp.role_id=p.role_id and rp.permission_code=p_permission
    where p.id=auth.uid()
    limit 1
  ),false);
$$;

create or replace function public.cce_is_booking_record(p_notes text)
returns boolean language sql immutable as $$
  select coalesce(p_notes,'') ilike '%BOOKING REQUEST%'
      or coalesce(p_notes,'') ilike '%TRAINING REQUEST%'
      or coalesce(p_notes,'') ilike '%LIVERY REQUEST%';
$$;

create or replace function public.cce_my_access()
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
  select jsonb_build_object(
    'profile',jsonb_build_object(
      'id',p.id,'email',p.email,'full_name',p.full_name,'phone',p.phone,
      'role_id',p.role_id,'is_active',p.is_active,'owner_name',p.owner_name,'instructor_id',p.instructor_id
    ),
    'role',jsonb_build_object('id',r.id,'code',r.code,'name_en',r.name_en,'name_ar',r.name_ar),
    'portal',case when r.code='owner' then 'owner' when r.code='trainer' then 'trainer' else 'dashboard' end,
    'instructor_name',(select i.name from public.instructors i where i.id=p.instructor_id limit 1),
    'permissions',coalesce((
      select jsonb_agg(ap.code order by ap.code)
      from public.app_permissions ap
      where public.cce_has_permission(ap.code)
    ),'[]'::jsonb)
  )
  from public.profiles p
  left join public.app_roles r on r.id=p.role_id
  where p.id=auth.uid() and p.is_active is true
  limit 1;
$$;

-- Public booking selector. It intentionally exposes only horse id and name.
create or replace function public.cce_public_available_horses()
returns table(id bigint,horse_name text)
language sql
stable
security definer
set search_path=public
as $$
  select h.id,h.horse_name from public.horses h
  where h.owner='CC' and h.status='Available' and h.horse_name is not null
  order by h.horse_name;
$$;

-- Authenticated owner access uses the profile mapping and never accepts a password or owner name from the browser.
create or replace function public.cce_member_owner_horses()
returns setof jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare v_owner text;
begin
  if not public.cce_has_permission('owner.horses.view') then raise exception 'Permission denied'; end if;
  select owner_name into v_owner from public.profiles where id=auth.uid() and is_active=true;
  if coalesce(trim(v_owner),'')='' then raise exception 'Owner mapping is missing'; end if;
  return query select to_jsonb(h)-'owner_pwd' from public.horses h
    where lower(trim(h.owner))=lower(trim(v_owner)) order by h.horse_name;
end;
$$;

create or replace function public.cce_member_owner_update_horse(
  p_horse_id bigint,
  p_horse_name text default null,
  p_contact text default null,
  p_cpr text default null,
  p_address text default null,
  p_sex text default null,
  p_color text default null,
  p_breed text default null,
  p_birth_date date default null,
  p_microchip text default null,
  p_passport text default null,
  p_farrier_name text default null,
  p_farrier_date date default null,
  p_vaccine_dr text default null,
  p_vaccine_date date default null,
  p_deworm_date date default null,
  p_teeth_date date default null,
  p_medicant text default null,
  p_med_date date default null
)
returns setof jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_owner text;
begin
  if not public.cce_has_permission('owner.horses.update') then raise exception 'Permission denied'; end if;
  select owner_name into v_owner from public.profiles where id=auth.uid() and is_active=true;
  if coalesce(trim(v_owner),'')='' then raise exception 'Owner mapping is missing'; end if;
  return query
  with changed as (
    update public.horses h set
      horse_name=p_horse_name,contact=p_contact,cpr=p_cpr,address=p_address,sex=p_sex,color=p_color,breed=p_breed,
      birth_date=p_birth_date,microchip=p_microchip,passport=p_passport,farrier_name=p_farrier_name,farrier_date=p_farrier_date,
      vaccine_dr=p_vaccine_dr,vaccine_date=p_vaccine_date,deworm_date=p_deworm_date,teeth_date=p_teeth_date,
      medicant=p_medicant,med_date=p_med_date
    where h.id=p_horse_id and lower(trim(h.owner))=lower(trim(v_owner))
    returning h.*
  ) select to_jsonb(changed)-'owner_pwd' from changed;
  if not found then raise exception 'Horse not found or not linked to this owner'; end if;
end;
$$;

create or replace function public.cce_member_instructor_schedule()
returns setof jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare v_name text;
begin
  if not public.cce_has_permission('schedule.view_own') then raise exception 'Permission denied'; end if;
  select i.name into v_name from public.profiles p join public.instructors i on i.id=p.instructor_id
  where p.id=auth.uid() and p.is_active=true and i.active is true;
  if coalesce(trim(v_name),'')='' then raise exception 'Instructor mapping is missing or inactive'; end if;
  return query select to_jsonb(s) from public.schedule s
  where lower(trim(s.instructor))=lower(trim(v_name))
  order by s.date,s.start_time;
end;
$$;

create or replace function public.cce_member_instructor_update_schedule(
  p_schedule_id bigint,
  p_status text default null,
  p_notes text default null
)
returns setof jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_name text;
begin
  if not public.cce_has_permission('schedule.update_own') then raise exception 'Permission denied'; end if;
  select i.name into v_name from public.profiles p join public.instructors i on i.id=p.instructor_id
  where p.id=auth.uid() and p.is_active=true and i.active is true;
  if coalesce(trim(v_name),'')='' then raise exception 'Instructor mapping is missing or inactive'; end if;
  return query
  with changed as (
    update public.schedule s set
      status=coalesce(p_status,s.status),
      notes=case when p_notes is null then s.notes else p_notes end
    where s.id=p_schedule_id and lower(trim(s.instructor))=lower(trim(v_name))
    returning s.*
  ) select to_jsonb(changed) from changed;
  if not found then raise exception 'Schedule row not found or not linked to this trainer'; end if;
end;
$$;

-- Remove access to old password/name-based portal functions when they exist.
do $$
begin
  if to_regprocedure('public.cce_owner_get_horses(text)') is not null then
    execute 'revoke all on function public.cce_owner_get_horses(text) from public,anon,authenticated';
  end if;
  if to_regprocedure('public.cce_owner_update_horse(bigint,text,text,text,text,text,text,text,text,date,text,text,text,date,text,date,date,date,text,date)') is not null then
    execute 'revoke all on function public.cce_owner_update_horse(bigint,text,text,text,text,text,text,text,text,date,text,text,text,date,text,date,date,date,text,date) from public,anon,authenticated';
  end if;
  if to_regprocedure('public.cce_instructor_login(text,text)') is not null then
    execute 'revoke all on function public.cce_instructor_login(text,text) from public,anon,authenticated';
  end if;
  if to_regprocedure('public.cce_instructor_schedule(text)') is not null then
    execute 'revoke all on function public.cce_instructor_schedule(text) from public,anon,authenticated';
  end if;
  if to_regprocedure('public.cce_instructor_update_schedule(bigint,text,text,text)') is not null then
    execute 'revoke all on function public.cce_instructor_update_schedule(bigint,text,text,text) from public,anon,authenticated';
  end if;
end $$;

-- PostgreSQL grants EXECUTE to PUBLIC by default; explicitly restrict member RPCs.
revoke all on function public.cce_has_permission(text) from public,anon;
revoke all on function public.cce_my_access() from public,anon;
revoke all on function public.cce_member_owner_horses() from public,anon;
revoke all on function public.cce_member_owner_update_horse(bigint,text,text,text,text,text,text,text,date,text,text,text,date,text,date,date,date,text,date) from public,anon;
revoke all on function public.cce_member_instructor_schedule() from public,anon;
revoke all on function public.cce_member_instructor_update_schedule(bigint,text,text) from public,anon;

revoke all on function public.cce_public_available_horses() from public;
grant execute on function public.cce_public_available_horses() to anon,authenticated;
grant execute on function public.cce_has_permission(text) to authenticated;
grant execute on function public.cce_my_access() to authenticated;
grant execute on function public.cce_member_owner_horses() to authenticated;
grant execute on function public.cce_member_owner_update_horse(bigint,text,text,text,text,text,text,text,date,text,text,text,date,text,date,date,date,text,date) to authenticated;
grant execute on function public.cce_member_instructor_schedule() to authenticated;
grant execute on function public.cce_member_instructor_update_schedule(bigint,text,text) to authenticated;

-- RBAC tables are administered through the protected Edge Function, not directly from browsers.
alter table public.app_roles enable row level security;
alter table public.app_permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.user_permissions enable row level security;
alter table public.profiles enable row level security;
alter table public.audit_logs enable row level security;

revoke all on public.app_roles,public.app_permissions,public.role_permissions,public.user_permissions,public.profiles from anon,authenticated;
grant select on public.profiles to authenticated;
grant insert on public.audit_logs to authenticated;
grant select on public.audit_logs to authenticated;

drop policy if exists cce_profile_self_select on public.profiles;
create policy cce_profile_self_select on public.profiles for select to authenticated
using (id=auth.uid());

drop policy if exists cce_audit_insert on public.audit_logs;
create policy cce_audit_insert on public.audit_logs for insert to authenticated
with check (exists (select 1 from public.profiles p where p.id=auth.uid() and p.is_active=true));

drop policy if exists cce_audit_select on public.audit_logs;
create policy cce_audit_select on public.audit_logs for select to authenticated
using (public.cce_has_permission('audit.view'));

-- Apply table privileges and RLS only when each legacy table exists.
-- Anonymous sequence access is reset and granted only to the public booking identity sequence.
revoke usage,select on all sequences in schema public from anon;
do $$
declare
  v_income_seq text;
begin
  if to_regclass('public.income') is not null then
    execute 'alter table public.income enable row level security';
    execute 'drop policy if exists income_public_request_insert on public.income';
    execute 'grant select,insert,update,delete on public.income to authenticated';
    execute 'grant insert on public.income to anon';
    v_income_seq := pg_get_serial_sequence('public.income','id');
    if v_income_seq is not null then
      execute format('grant usage on sequence %s to anon',v_income_seq);
    end if;
    execute 'drop policy if exists cce_income_public_insert on public.income';
    execute $p$create policy cce_income_public_insert on public.income for insert to anon with check (
      coalesce(status,'Pending')='Pending' and coalesce(paid_bd,0)=0 and public.cce_is_booking_record(notes)
    )$p$;
    execute 'drop policy if exists cce_income_select on public.income';
    execute $p$create policy cce_income_select on public.income for select to authenticated using (
      public.cce_has_permission('income.view') or (public.cce_has_permission('bookings.view') and public.cce_is_booking_record(notes))
    )$p$;
    execute 'drop policy if exists cce_income_insert on public.income';
    execute $p$create policy cce_income_insert on public.income for insert to authenticated with check (
      public.cce_has_permission('income.create') or (public.cce_has_permission('bookings.create') and public.cce_is_booking_record(notes))
    )$p$;
    execute 'drop policy if exists cce_income_update on public.income';
    execute $p$create policy cce_income_update on public.income for update to authenticated using (
      public.cce_has_permission('income.update') or (public.cce_has_permission('bookings.update') and public.cce_is_booking_record(notes))
    ) with check (
      public.cce_has_permission('income.update') or (public.cce_has_permission('bookings.update') and public.cce_is_booking_record(notes))
    )$p$;
    execute 'drop policy if exists cce_income_delete on public.income';
    execute $p$create policy cce_income_delete on public.income for delete to authenticated using (
      public.cce_has_permission('income.delete') or (public.cce_has_permission('bookings.delete') and public.cce_is_booking_record(notes))
    )$p$;
  end if;

  if to_regclass('public.expenses') is not null then
    execute 'alter table public.expenses enable row level security';
    execute 'grant select,insert,update,delete on public.expenses to authenticated';
    execute 'drop policy if exists cce_expenses_select on public.expenses';
    execute $p$create policy cce_expenses_select on public.expenses for select to authenticated using (public.cce_has_permission('expenses.view'))$p$;
    execute 'drop policy if exists cce_expenses_insert on public.expenses';
    execute $p$create policy cce_expenses_insert on public.expenses for insert to authenticated with check (public.cce_has_permission('expenses.create'))$p$;
    execute 'drop policy if exists cce_expenses_update on public.expenses';
    execute $p$create policy cce_expenses_update on public.expenses for update to authenticated using (public.cce_has_permission('expenses.update')) with check (public.cce_has_permission('expenses.update'))$p$;
    execute 'drop policy if exists cce_expenses_delete on public.expenses';
    execute $p$create policy cce_expenses_delete on public.expenses for delete to authenticated using (public.cce_has_permission('expenses.delete'))$p$;
  end if;

  if to_regclass('public.horses') is not null then
    execute 'alter table public.horses enable row level security';
    execute 'grant select,insert,update,delete on public.horses to authenticated';
    execute 'drop policy if exists cce_horses_select on public.horses';
    execute $p$create policy cce_horses_select on public.horses for select to authenticated using (public.cce_has_permission('horses.view'))$p$;
    execute 'drop policy if exists cce_horses_insert on public.horses';
    execute $p$create policy cce_horses_insert on public.horses for insert to authenticated with check (public.cce_has_permission('horses.create'))$p$;
    execute 'drop policy if exists cce_horses_update on public.horses';
    execute $p$create policy cce_horses_update on public.horses for update to authenticated using (public.cce_has_permission('horses.update')) with check (public.cce_has_permission('horses.update'))$p$;
    execute 'drop policy if exists cce_horses_delete on public.horses';
    execute $p$create policy cce_horses_delete on public.horses for delete to authenticated using (public.cce_has_permission('horses.delete'))$p$;
  end if;

  if to_regclass('public.breeding') is not null then
    execute 'alter table public.breeding enable row level security';
    execute 'grant select,insert,update,delete on public.breeding to authenticated';
    execute 'drop policy if exists cce_breeding_select on public.breeding';
    execute $p$create policy cce_breeding_select on public.breeding for select to authenticated using (public.cce_has_permission('breeding.view'))$p$;
    execute 'drop policy if exists cce_breeding_insert on public.breeding';
    execute $p$create policy cce_breeding_insert on public.breeding for insert to authenticated with check (public.cce_has_permission('breeding.create'))$p$;
    execute 'drop policy if exists cce_breeding_update on public.breeding';
    execute $p$create policy cce_breeding_update on public.breeding for update to authenticated using (public.cce_has_permission('breeding.update')) with check (public.cce_has_permission('breeding.update'))$p$;
    execute 'drop policy if exists cce_breeding_delete on public.breeding';
    execute $p$create policy cce_breeding_delete on public.breeding for delete to authenticated using (public.cce_has_permission('breeding.delete'))$p$;
  end if;

  if to_regclass('public.schedule') is not null then
    execute 'alter table public.schedule enable row level security';
    execute 'grant select,insert,update,delete on public.schedule to authenticated';
    execute 'drop policy if exists cce_schedule_select on public.schedule';
    execute $p$create policy cce_schedule_select on public.schedule for select to authenticated using (public.cce_has_permission('schedule.view'))$p$;
    execute 'drop policy if exists cce_schedule_insert on public.schedule';
    execute $p$create policy cce_schedule_insert on public.schedule for insert to authenticated with check (public.cce_has_permission('schedule.create'))$p$;
    execute 'drop policy if exists cce_schedule_update on public.schedule';
    execute $p$create policy cce_schedule_update on public.schedule for update to authenticated using (public.cce_has_permission('schedule.update')) with check (public.cce_has_permission('schedule.update'))$p$;
    execute 'drop policy if exists cce_schedule_delete on public.schedule';
    execute $p$create policy cce_schedule_delete on public.schedule for delete to authenticated using (public.cce_has_permission('schedule.delete'))$p$;
  end if;

  if to_regclass('public.instructors') is not null then
    execute 'alter table public.instructors enable row level security';
    execute 'grant select,insert,update,delete on public.instructors to authenticated';
    execute 'drop policy if exists cce_instructors_select on public.instructors';
    execute $p$create policy cce_instructors_select on public.instructors for select to authenticated using (public.cce_has_permission('instructors.view') or public.cce_has_permission('schedule.view'))$p$;
    execute 'drop policy if exists cce_instructors_insert on public.instructors';
    execute $p$create policy cce_instructors_insert on public.instructors for insert to authenticated with check (public.cce_has_permission('instructors.create'))$p$;
    execute 'drop policy if exists cce_instructors_update on public.instructors';
    execute $p$create policy cce_instructors_update on public.instructors for update to authenticated using (public.cce_has_permission('instructors.update')) with check (public.cce_has_permission('instructors.update'))$p$;
    execute 'drop policy if exists cce_instructors_delete on public.instructors';
    execute $p$create policy cce_instructors_delete on public.instructors for delete to authenticated using (public.cce_has_permission('instructors.delete'))$p$;
  end if;
end $$;

grant usage,select on all sequences in schema public to authenticated;

commit;
