-- CCE StableOS v4.10.0 — Show Office Sprint 2
-- Competition classes, independent permissions, RLS and atomic module restore.

begin;

do $$
begin
  if to_regclass('public.show_office_competitions') is null
     or to_regclass('public.app_permissions') is null
     or to_regclass('public.app_roles') is null
     or to_regclass('public.role_permissions') is null
     or to_regprocedure('public.cce_has_permission(text)') is null
     or to_regprocedure('public.cce_restore_show_office_competitions(jsonb)') is null then
    raise exception 'Show Office v4.9.1 must be applied before Sprint 2';
  end if;
end $$;

insert into public.app_permissions(code,category,name_en,name_ar) values
('show_office.classes.view','Show Office','View competition classes','عرض فئات البطولات'),
('show_office.classes.create','Show Office','Create competition classes','إضافة فئات البطولات'),
('show_office.classes.update','Show Office','Update competition classes','تعديل فئات البطولات'),
('show_office.classes.delete','Show Office','Delete competition classes','حذف فئات البطولات')
on conflict(code) do update set
  category=excluded.category,
  name_en=excluded.name_en,
  name_ar=excluded.name_ar;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true
from public.app_roles r
join public.app_permissions p on p.code like 'show_office.classes.%'
where r.code in ('super_admin','manager')
on conflict(role_id,permission_code) do update set allowed=true;

create table if not exists public.show_office_classes (
  id bigint generated by default as identity primary key,
  competition_id bigint not null references public.show_office_competitions(id) on delete restrict,
  class_number text not null,
  sort_order integer not null,
  class_name text not null,
  height_cm smallint,
  competition_type text not null,
  allowed_time_seconds integer,
  time_limit_seconds integer,
  jump_off boolean not null default false,
  entry_fee_bd numeric(10,3) not null default 0,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint show_office_classes_number_required check (length(trim(class_number))>0),
  constraint show_office_classes_number_length_check check (char_length(trim(class_number))<=30),
  constraint show_office_classes_sort_order_check check (sort_order>0),
  constraint show_office_classes_name_required check (length(trim(class_name))>0),
  constraint show_office_classes_name_length_check check (char_length(trim(class_name))<=180),
  constraint show_office_classes_height_check check (height_cm is null or height_cm>0),
  constraint show_office_classes_type_required check (length(trim(competition_type))>0),
  constraint show_office_classes_type_length_check check (char_length(trim(competition_type))<=120),
  constraint show_office_classes_allowed_time_check check (allowed_time_seconds is null or allowed_time_seconds>0),
  constraint show_office_classes_time_limit_check check (time_limit_seconds is null or time_limit_seconds>0),
  constraint show_office_classes_time_order_check check (
    allowed_time_seconds is null or time_limit_seconds is null or time_limit_seconds>=allowed_time_seconds
  ),
  constraint show_office_classes_entry_fee_check check (entry_fee_bd>=0),
  constraint show_office_classes_notes_length_check check (char_length(coalesce(notes,''))<=4000)
);

create unique index if not exists show_office_classes_competition_number_uidx
  on public.show_office_classes(competition_id,lower(trim(class_number)));
create index if not exists show_office_classes_competition_order_idx
  on public.show_office_classes(competition_id,sort_order,id);
create index if not exists show_office_classes_type_idx
  on public.show_office_classes(competition_type);

create or replace function public.cce_show_office_stamp_class()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if tg_op='INSERT' then
    new.created_by=auth.uid();
    new.created_at=coalesce(new.created_at,now());
  else
    new.created_by=old.created_by;
    new.created_at=old.created_at;
  end if;
  new.updated_by=auth.uid();
  new.updated_at=now();
  return new;
end;
$$;

drop trigger if exists show_office_classes_stamp on public.show_office_classes;
create trigger show_office_classes_stamp
before insert or update on public.show_office_classes
for each row execute function public.cce_show_office_stamp_class();

alter table public.show_office_classes enable row level security;

revoke all on public.show_office_classes from public,anon,authenticated;
grant select,insert,update,delete on public.show_office_classes to authenticated;
grant usage,select on sequence public.show_office_classes_id_seq to authenticated;

drop policy if exists cce_show_office_classes_select on public.show_office_classes;
create policy cce_show_office_classes_select
on public.show_office_classes for select to authenticated
using (
  public.cce_has_permission('show_office.view')
  or public.cce_has_permission('show_office.classes.view')
);

drop policy if exists cce_show_office_classes_insert on public.show_office_classes;
create policy cce_show_office_classes_insert
on public.show_office_classes for insert to authenticated
with check (public.cce_has_permission('show_office.classes.create'));

drop policy if exists cce_show_office_classes_update on public.show_office_classes;
create policy cce_show_office_classes_update
on public.show_office_classes for update to authenticated
using (public.cce_has_permission('show_office.classes.update'))
with check (public.cce_has_permission('show_office.classes.update'));

drop policy if exists cce_show_office_classes_delete on public.show_office_classes;
create policy cce_show_office_classes_delete
on public.show_office_classes for delete to authenticated
using (public.cce_has_permission('show_office.classes.delete'));

-- Full competition records remain protected by the competition-view permissions.
drop policy if exists cce_show_office_competitions_select on public.show_office_competitions;
create policy cce_show_office_competitions_select
on public.show_office_competitions for select to authenticated
using (
  public.cce_has_permission('show_office.view')
  or public.cce_has_permission('show_office.competitions.view')
);

-- A classes-only operator resolves parents through this deliberately narrow
-- directory instead of receiving SELECT access to every competition column.
create or replace function public.cce_show_office_class_competitions()
returns table(id bigint,competition_name text,competition_date date)
language plpgsql
stable
security definer
set search_path=public
as $$
begin
  if not (
    public.cce_has_permission('show_office.view')
    or public.cce_has_permission('show_office.competitions.view')
    or public.cce_has_permission('show_office.classes.view')
  ) then
    raise exception 'Permission denied: Show Office class view permission is required'
      using errcode='42501';
  end if;

  return query
  select c.id,c.competition_name,c.competition_date
  from public.show_office_competitions c
  order by c.competition_date desc,c.id desc;
end;
$$;

revoke all on function public.cce_show_office_class_competitions() from public,anon,authenticated;
grant execute on function public.cce_show_office_class_competitions() to authenticated;

revoke all on function public.cce_show_office_stamp_class() from public,anon,authenticated;

create or replace function public.cce_restore_show_office_module(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_competitions jsonb;
  v_classes jsonb;
  v_row jsonb;
  v_index integer:=0;
  v_field text;
  v_date_text text;
  v_date date;
  v_allowed integer;
  v_limit integer;
  v_competition_id bigint;
  v_inserted_id bigint;
  v_competition_summary jsonb;
  v_class_total integer:=0;
  v_class_imported integer:=0;
  v_class_duplicates integer:=0;
begin
  if not public.cce_has_permission('show_office.competitions.create')
     or not public.cce_has_permission('show_office.classes.create') then
    raise exception 'Permission denied: Show Office competition and class create permissions are required'
      using errcode='42501';
  end if;
  if p_payload is null or jsonb_typeof(p_payload)<>'object' then
    raise exception 'Show Office restore payload must be a JSON object' using errcode='22023';
  end if;

  v_competitions:=p_payload->'competitions';
  v_classes:=coalesce(p_payload->'classes','[]'::jsonb);
  if v_competitions is null or jsonb_typeof(v_competitions)<>'array' then
    raise exception 'Show Office restore competitions must be a JSON array' using errcode='22023';
  end if;
  if jsonb_typeof(v_classes)<>'array' then
    raise exception 'Show Office restore classes must be a JSON array' using errcode='22023';
  end if;

  v_class_total:=jsonb_array_length(v_classes);
  -- Validate every class and its portable parent reference before any insert.
  for v_row in select value from jsonb_array_elements(v_classes)
  loop
    v_index:=v_index+1;
    if jsonb_typeof(v_row)<>'object' then
      raise exception 'Show Office backup class % must be an object',v_index using errcode='22023';
    end if;
    foreach v_field in array array[
      'competition_name','competition_date','class_number','class_name','competition_type','notes'
    ]
    loop
      if v_row?v_field and jsonb_typeof(v_row->v_field) not in ('string','null') then
        raise exception 'Show Office backup class % field % must be text',v_index,v_field using errcode='22023';
      end if;
    end loop;
    foreach v_field in array array[
      'sort_order','height_cm','allowed_time_seconds','time_limit_seconds','entry_fee_bd'
    ]
    loop
      if v_row?v_field and jsonb_typeof(v_row->v_field) not in ('number','null') then
        raise exception 'Show Office backup class % field % must be numeric',v_index,v_field using errcode='22023';
      end if;
    end loop;
    if v_row?'jump_off' and jsonb_typeof(v_row->'jump_off') not in ('boolean','null') then
      raise exception 'Show Office backup class % field jump_off must be boolean',v_index using errcode='22023';
    end if;

    if btrim(coalesce(v_row->>'competition_name',''))='' then
      raise exception 'Show Office backup class % requires competition_name',v_index using errcode='22023';
    end if;
    if char_length(btrim(v_row->>'competition_name'))>180 then
      raise exception 'Show Office backup class % competition name exceeds 180 characters',v_index using errcode='22023';
    end if;
    v_date_text:=v_row->>'competition_date';
    if v_date_text is null or v_date_text!~'^\d{4}-\d{2}-\d{2}$' then
      raise exception 'Show Office backup class % has invalid competition_date',v_index using errcode='22023';
    end if;
    begin
      v_date:=v_date_text::date;
    exception when others then
      raise exception 'Show Office backup class % has invalid competition_date',v_index using errcode='22023';
    end;
    if to_char(v_date,'YYYY-MM-DD')<>v_date_text then
      raise exception 'Show Office backup class % has invalid competition_date',v_index using errcode='22023';
    end if;
    if not exists(
      select 1 from public.show_office_competitions c
      where lower(trim(c.competition_name))=lower(btrim(v_row->>'competition_name'))
        and c.competition_date=v_date
    ) and not exists(
      select 1 from jsonb_array_elements(v_competitions) c(value)
      where lower(btrim(c.value->>'competition_name'))=lower(btrim(v_row->>'competition_name'))
        and c.value->>'competition_date'=v_date_text
    ) then
      raise exception 'Show Office backup class % references an unavailable competition',v_index using errcode='23503';
    end if;

    if btrim(coalesce(v_row->>'class_number',''))='' then
      raise exception 'Show Office backup class % requires class_number',v_index using errcode='22023';
    end if;
    if char_length(btrim(v_row->>'class_number'))>30 then
      raise exception 'Show Office backup class % number exceeds 30 characters',v_index using errcode='22023';
    end if;
    if btrim(coalesce(v_row->>'class_name',''))='' or char_length(btrim(v_row->>'class_name'))>180 then
      raise exception 'Show Office backup class % has an invalid class_name',v_index using errcode='22023';
    end if;
    if btrim(coalesce(v_row->>'competition_type',''))='' or char_length(btrim(v_row->>'competition_type'))>120 then
      raise exception 'Show Office backup class % has an invalid competition_type',v_index using errcode='22023';
    end if;
    if char_length(btrim(coalesce(v_row->>'notes','')))>4000 then
      raise exception 'Show Office backup class % notes exceed 4000 characters',v_index using errcode='22023';
    end if;

    if not (v_row?'sort_order') or jsonb_typeof(v_row->'sort_order')<>'number'
       or (v_row->>'sort_order')::numeric<>trunc((v_row->>'sort_order')::numeric)
       or (v_row->>'sort_order')::numeric<=0
       or (v_row->>'sort_order')::numeric>2147483647 then
      raise exception 'Show Office backup class % has invalid sort_order',v_index using errcode='22023';
    end if;
    if v_row->'height_cm' is not null and jsonb_typeof(v_row->'height_cm')<>'null' and (
      (v_row->>'height_cm')::numeric<>trunc((v_row->>'height_cm')::numeric)
      or (v_row->>'height_cm')::numeric<=0 or (v_row->>'height_cm')::numeric>32767
    ) then
      raise exception 'Show Office backup class % has invalid height_cm',v_index using errcode='22023';
    end if;
    if v_row->'allowed_time_seconds' is not null and jsonb_typeof(v_row->'allowed_time_seconds')<>'null' and (
      (v_row->>'allowed_time_seconds')::numeric<>trunc((v_row->>'allowed_time_seconds')::numeric)
      or (v_row->>'allowed_time_seconds')::numeric<=0 or (v_row->>'allowed_time_seconds')::numeric>2147483647
    ) then
      raise exception 'Show Office backup class % has invalid allowed_time_seconds',v_index using errcode='22023';
    end if;
    if v_row->'time_limit_seconds' is not null and jsonb_typeof(v_row->'time_limit_seconds')<>'null' and (
      (v_row->>'time_limit_seconds')::numeric<>trunc((v_row->>'time_limit_seconds')::numeric)
      or (v_row->>'time_limit_seconds')::numeric<=0 or (v_row->>'time_limit_seconds')::numeric>2147483647
    ) then
      raise exception 'Show Office backup class % has invalid time_limit_seconds',v_index using errcode='22023';
    end if;
    v_allowed:=nullif(v_row->>'allowed_time_seconds','')::integer;
    v_limit:=nullif(v_row->>'time_limit_seconds','')::integer;
    if v_allowed is not null and v_limit is not null and v_limit<v_allowed then
      raise exception 'Show Office backup class % time limit is below allowed time',v_index using errcode='22023';
    end if;
    if v_row->'entry_fee_bd' is not null and jsonb_typeof(v_row->'entry_fee_bd')<>'null' and (
      (v_row->>'entry_fee_bd')::numeric<0 or (v_row->>'entry_fee_bd')::numeric>9999999.999
      or scale((v_row->>'entry_fee_bd')::numeric)>3
    ) then
      raise exception 'Show Office backup class % has invalid entry_fee_bd',v_index using errcode='22023';
    end if;
  end loop;

  -- The v4.9.1 function validates and restores competitions. Any later class
  -- failure still rolls back those inserts because this RPC is one transaction.
  select public.cce_restore_show_office_competitions(v_competitions)
  into v_competition_summary;

  for v_row in select value from jsonb_array_elements(v_classes)
  loop
    v_date:=(v_row->>'competition_date')::date;
    select c.id into strict v_competition_id
    from public.show_office_competitions c
    where lower(trim(c.competition_name))=lower(btrim(v_row->>'competition_name'))
      and c.competition_date=v_date;

    v_inserted_id:=null;
    insert into public.show_office_classes(
      competition_id,class_number,sort_order,class_name,height_cm,competition_type,
      allowed_time_seconds,time_limit_seconds,jump_off,entry_fee_bd,notes
    ) values(
      v_competition_id,
      btrim(v_row->>'class_number'),
      (v_row->>'sort_order')::integer,
      btrim(v_row->>'class_name'),
      nullif(v_row->>'height_cm','')::smallint,
      btrim(v_row->>'competition_type'),
      nullif(v_row->>'allowed_time_seconds','')::integer,
      nullif(v_row->>'time_limit_seconds','')::integer,
      coalesce((v_row->>'jump_off')::boolean,false),
      coalesce((v_row->>'entry_fee_bd')::numeric,0),
      nullif(btrim(coalesce(v_row->>'notes','')),'')
    )
    on conflict do nothing
    returning id into v_inserted_id;
    if v_inserted_id is null then
      v_class_duplicates:=v_class_duplicates+1;
    else
      v_class_imported:=v_class_imported+1;
    end if;
  end loop;

  return jsonb_build_object(
    'module','showOffice',
    'total',(v_competition_summary->>'total')::integer+v_class_total,
    'imported',(v_competition_summary->>'imported')::integer+v_class_imported,
    'duplicates',(v_competition_summary->>'duplicates')::integer+v_class_duplicates,
    'invalid',0,
    'entities',jsonb_build_object(
      'competitions',v_competition_summary-'module',
      'classes',jsonb_build_object(
        'total',v_class_total,'imported',v_class_imported,
        'duplicates',v_class_duplicates,'invalid',0
      )
    )
  );
end;
$$;

revoke all on function public.cce_restore_show_office_module(jsonb) from public,anon,authenticated;
grant execute on function public.cce_restore_show_office_module(jsonb) to authenticated;

comment on table public.show_office_classes is
  'Show Office competition classes. Entries reference these records starting in Sprint 3.';
comment on column public.show_office_classes.class_number is
  'Display identifier such as 1 or 1A; sort_order controls operational order.';
comment on function public.cce_show_office_class_competitions() is
  'Returns only id, name and date for competition selectors used by class-view operators.';
comment on function public.cce_restore_show_office_module(jsonb) is
  'Atomically restores portable Show Office competitions and classes without trusting IDs or audit fields.';

commit;
