-- CCE Stable Management Pro — Phase 1
-- Horse status, medical records, vaccinations, treatments and care alerts.
begin;

insert into public.app_permissions(code,category,name_en,name_ar) values
('horse_health.view','Horse Health','View horse health profiles','عرض الملفات الصحية للخيل'),
('horse_health.manage','Horse Health','Manage horse health profiles','إدارة الملفات الصحية للخيل'),
('horse_medical.view','Horse Health','View medical records','عرض السجلات الطبية'),
('horse_medical.manage','Horse Health','Manage medical records','إدارة السجلات الطبية'),
('horse_vaccinations.view','Horse Health','View vaccinations','عرض التطعيمات'),
('horse_vaccinations.manage','Horse Health','Manage vaccinations','إدارة التطعيمات'),
('horse_care.view','Horse Health','View care tasks and alerts','عرض مهام وتنبيهات العناية'),
('horse_care.manage','Horse Health','Manage care tasks and alerts','إدارة مهام وتنبيهات العناية')
on conflict (code) do update set category=excluded.category,name_en=excluded.name_en,name_ar=excluded.name_ar;

create table if not exists public.horse_health_profiles (
  id bigint generated by default as identity primary key,
  horse_id bigint not null unique references public.horses(id) on delete cascade,
  health_status text not null default 'Healthy' check (health_status in ('Healthy','Training','Injured','Under Treatment','Pregnant','Resting','Isolation','Critical')),
  severity text not null default 'None' check (severity in ('None','Low','Moderate','High','Critical')),
  diagnosis text,
  current_medication text,
  veterinarian text,
  next_review_date date,
  pregnant_since date,
  expected_foaling_date date,
  isolation_reason text,
  allergies text,
  medical_notes text,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.horse_medical_records (
  id bigint generated by default as identity primary key,
  horse_id bigint not null references public.horses(id) on delete cascade,
  record_type text not null default 'Medical' check (record_type in ('Medical','Injury','Treatment','Veterinary Visit','Surgery','Dental','Farrier','Deworming')),
  event_date date not null default current_date,
  title text not null,
  diagnosis text,
  treatment text,
  medication text,
  veterinarian text,
  severity text default 'Low' check (severity in ('Low','Moderate','High','Critical')),
  next_review_date date,
  status text not null default 'Open' check (status in ('Open','Monitoring','Completed','Cancelled')),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.horse_vaccinations (
  id bigint generated by default as identity primary key,
  horse_id bigint not null references public.horses(id) on delete cascade,
  vaccine_name text not null,
  administered_date date,
  due_date date not null,
  veterinarian text,
  batch_number text,
  status text not null default 'Pending' check (status in ('Pending','Completed','Overdue','Cancelled')),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.horse_care_tasks (
  id bigint generated by default as identity primary key,
  horse_id bigint not null references public.horses(id) on delete cascade,
  task_type text not null check (task_type in ('Veterinary','Medication','Farrier','Dental','Deworming','Vaccination','Rest','Observation','Other')),
  title text not null,
  due_date date not null,
  priority text not null default 'Normal' check (priority in ('Low','Normal','High','Urgent')),
  status text not null default 'Pending' check (status in ('Pending','Completed','Cancelled')),
  assigned_to text,
  notes text,
  completed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists horse_health_status_idx on public.horse_health_profiles(health_status);
create index if not exists horse_health_review_idx on public.horse_health_profiles(next_review_date);
create index if not exists horse_medical_horse_date_idx on public.horse_medical_records(horse_id,event_date desc);
create index if not exists horse_vaccinations_due_idx on public.horse_vaccinations(due_date,status);
create index if not exists horse_care_due_idx on public.horse_care_tasks(due_date,status);

create or replace function public.cce_touch_horse_health_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;

do $$ begin
  if not exists (select 1 from pg_trigger where tgname='horse_health_profiles_touch') then
    create trigger horse_health_profiles_touch before update on public.horse_health_profiles for each row execute function public.cce_touch_horse_health_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname='horse_medical_records_touch') then
    create trigger horse_medical_records_touch before update on public.horse_medical_records for each row execute function public.cce_touch_horse_health_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname='horse_vaccinations_touch') then
    create trigger horse_vaccinations_touch before update on public.horse_vaccinations for each row execute function public.cce_touch_horse_health_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname='horse_care_tasks_touch') then
    create trigger horse_care_tasks_touch before update on public.horse_care_tasks for each row execute function public.cce_touch_horse_health_updated_at();
  end if;
end $$;

-- Grant new permissions to operational roles.
insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true from public.app_roles r join public.app_permissions p on p.code in (
'horse_health.view','horse_health.manage','horse_medical.view','horse_medical.manage',
'horse_vaccinations.view','horse_vaccinations.manage','horse_care.view','horse_care.manage'
) where r.code in ('super_admin','manager')
on conflict (role_id,permission_code) do update set allowed=true;

insert into public.role_permissions(role_id,permission_code,allowed)
select r.id,p.code,true from public.app_roles r join public.app_permissions p on p.code in (
'horse_health.view','horse_medical.view','horse_medical.manage','horse_vaccinations.view','horse_care.view','horse_care.manage'
) where r.code in ('trainer','staff')
on conflict (role_id,permission_code) do nothing;

alter table public.horse_health_profiles enable row level security;
alter table public.horse_medical_records enable row level security;
alter table public.horse_vaccinations enable row level security;
alter table public.horse_care_tasks enable row level security;

drop policy if exists cce_hhp_select on public.horse_health_profiles;
create policy cce_hhp_select on public.horse_health_profiles for select to authenticated using (public.cce_has_permission('horse_health.view'));
drop policy if exists cce_hhp_insert on public.horse_health_profiles;
create policy cce_hhp_insert on public.horse_health_profiles for insert to authenticated with check (public.cce_has_permission('horse_health.manage'));
drop policy if exists cce_hhp_update on public.horse_health_profiles;
create policy cce_hhp_update on public.horse_health_profiles for update to authenticated using (public.cce_has_permission('horse_health.manage')) with check (public.cce_has_permission('horse_health.manage'));
drop policy if exists cce_hhp_delete on public.horse_health_profiles;
create policy cce_hhp_delete on public.horse_health_profiles for delete to authenticated using (public.cce_has_permission('horse_health.manage'));

drop policy if exists cce_hmr_select on public.horse_medical_records;
create policy cce_hmr_select on public.horse_medical_records for select to authenticated using (public.cce_has_permission('horse_medical.view'));
drop policy if exists cce_hmr_insert on public.horse_medical_records;
create policy cce_hmr_insert on public.horse_medical_records for insert to authenticated with check (public.cce_has_permission('horse_medical.manage'));
drop policy if exists cce_hmr_update on public.horse_medical_records;
create policy cce_hmr_update on public.horse_medical_records for update to authenticated using (public.cce_has_permission('horse_medical.manage')) with check (public.cce_has_permission('horse_medical.manage'));
drop policy if exists cce_hmr_delete on public.horse_medical_records;
create policy cce_hmr_delete on public.horse_medical_records for delete to authenticated using (public.cce_has_permission('horse_medical.manage'));

drop policy if exists cce_hv_select on public.horse_vaccinations;
create policy cce_hv_select on public.horse_vaccinations for select to authenticated using (public.cce_has_permission('horse_vaccinations.view'));
drop policy if exists cce_hv_insert on public.horse_vaccinations;
create policy cce_hv_insert on public.horse_vaccinations for insert to authenticated with check (public.cce_has_permission('horse_vaccinations.manage'));
drop policy if exists cce_hv_update on public.horse_vaccinations;
create policy cce_hv_update on public.horse_vaccinations for update to authenticated using (public.cce_has_permission('horse_vaccinations.manage')) with check (public.cce_has_permission('horse_vaccinations.manage'));
drop policy if exists cce_hv_delete on public.horse_vaccinations;
create policy cce_hv_delete on public.horse_vaccinations for delete to authenticated using (public.cce_has_permission('horse_vaccinations.manage'));

drop policy if exists cce_hct_select on public.horse_care_tasks;
create policy cce_hct_select on public.horse_care_tasks for select to authenticated using (public.cce_has_permission('horse_care.view'));
drop policy if exists cce_hct_insert on public.horse_care_tasks;
create policy cce_hct_insert on public.horse_care_tasks for insert to authenticated with check (public.cce_has_permission('horse_care.manage'));
drop policy if exists cce_hct_update on public.horse_care_tasks;
create policy cce_hct_update on public.horse_care_tasks for update to authenticated using (public.cce_has_permission('horse_care.manage')) with check (public.cce_has_permission('horse_care.manage'));
drop policy if exists cce_hct_delete on public.horse_care_tasks;
create policy cce_hct_delete on public.horse_care_tasks for delete to authenticated using (public.cce_has_permission('horse_care.manage'));

grant select,insert,update,delete on public.horse_health_profiles,public.horse_medical_records,public.horse_vaccinations,public.horse_care_tasks to authenticated;
grant usage,select on all sequences in schema public to authenticated;

commit;
